"""Generate exact street support from audited identity-transform source meshes."""
import argparse
import hashlib
import json
from pathlib import Path
from generate_crowd_kotel_ground import bounds, overlaps

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'Plugins/MikdashRuntime/Source/MikdashRuntime/Private/CrowdStreetGroundData.h'
INPUTS = {
    'audit': ('SourceAssets/perf-review/crowd-vat/street-native-mesh-20260919T010523238528Z.json', '446dd502d3e30d4290ace09f6eec3a1f9a01736d7f25af29fc4409dda2c97d38'),
    'fresh': ('SourceAssets/perf-review/crowd-vat/street-fallback-20260919T011719681520Z.json', '62c72856c4b02ebab708f209fc783e491baa6574ad828b9f2cd9f2a5aeeaa48d'),
    'zones': ('SourceAssets/runtime-review/crowd-field/zones.json', 'b6445cc2460f52d2dbf45158fff86d7e12a4a382c7af03a7f6c03249233d3b24'),
}


def render():
    data = {}
    for key, (name, digest) in INPUTS.items():
        raw = (ROOT / name).read_bytes()
        if hashlib.sha256(raw).hexdigest() != digest:
            raise ValueError('Pinned street evidence changed: ' + name)
        data[key] = json.loads(raw.decode('utf-8-sig'))
    fresh = data['fresh']
    if fresh['status'] != 'verified-fresh-native' or fresh['maximumSurfaceDifferenceCm'] != 0:
        raise ValueError('Missing terrain fallback fidelity proof')
    zone = next(z for z in data['zones']['zones'] if z['name'] == 'StreetBateiMahase')
    box = bounds(zone['polygonXYcm'])
    faces, counts = [], []
    for asset in data['audit']['assets']:
        digest = fresh['afterSha256'] if asset['asset'] == fresh['asset'] else asset['assetSha256Before']
        path = ROOT / ('Content/' + asset['asset'].removeprefix('/Game/') + '.uasset')
        if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise ValueError('Street source asset changed: ' + str(path))
        mesh = asset['geometry']['source']
        selected = [[mesh['vertices'][i] for i in f] for f in mesh['triangles']
                    if overlaps(bounds([mesh['vertices'][i] for i in f]), box)]
        counts.append(len(selected))
        faces.extend(selected)
    if counts != [8, 18]:
        raise ValueError('Reviewed street surface partition changed')
    lines = ['// Generated by Scripts/generate_crowd_street_ground.py; do not edit.',
             '// Highest terrain/asphalt source surface in world centimetres.',
             '// Requires the full-fidelity terrain fallback asset; never fitted to contacts.',
             '#pragma once', '#include "CrowdGroundMath.h"', 'namespace CrowdStreetGroundData {']
    for key, (_, digest) in INPUTS.items():
        lines.append(f'inline constexpr const char* {key}Sha256 = "{digest}";')
    lines.append('inline constexpr MikdashCrowdGround::Triangle Street[] = {')
    for face in faces:
        lines.append('{' + ','.join('{' + ','.join(format(v, '.17g') for v in p) + '}' for p in face) + '},')
    lines.append('};\n}\n')
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = render()
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != generated:
            raise SystemExit('Street ground header differs')
    else:
        OUTPUT.write_text(generated, encoding='utf-8', newline='\n')
    print('Street ground header verified' if args.check else 'Street ground header generated')
