"""Pinned Kotel crowd floor references; no Unreal or map/asset writes."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'Plugins/MikdashRuntime/Source/MikdashRuntime/Private/CrowdKotelGroundData.h'
INPUTS = {
    'terrain': ('SourceAssets/FutureMountV1/terrain-generated/SM_JerusalemTerrain_07_08_FutureMountCut.mesh.json', 'abc6152db1d10b80476870ac843bfde232b30ccac90733994e3ecf743579095a'),
    'deck': ('SourceAssets/context-review/KotelPlazaV1/kotel-plaza-plan.json', 'f3483bff589169159bc99200761d90230e4726ec248226c948f0ead6dedca69c'),
    'zones': ('SourceAssets/runtime-review/crowd-field/zones.json', 'b6445cc2460f52d2dbf45158fff86d7e12a4a382c7af03a7f6c03249233d3b24'),
}


def load():
    result = {}
    for key, (name, digest) in INPUTS.items():
        raw = (ROOT / name).read_bytes()
        if hashlib.sha256(raw).hexdigest() != digest:
            raise ValueError('Pinned crowd ground input changed: ' + name)
        result[key] = json.loads(raw.decode('utf-8-sig'))
    return result


def bounds(points):
    return (min(p[0] for p in points), min(p[1] for p in points),
            max(p[0] for p in points), max(p[1] for p in points))


def overlaps(a, b):
    return a[2] >= b[0] and a[0] <= b[2] and a[3] >= b[1] and a[1] <= b[3]


def geometry(data):
    zones = {z['name']: z for z in data['zones']['zones']}
    plaza = bounds(zones['KotelPlazaStrip']['polygonXYcm'])
    approach = bounds(zones['KotelApproachCorridor']['polygonXYcm'])
    decks, triangles = [], []
    for d in data['deck']['deck']:
        if d['rot'] != [0, 0, 0] or d['scale'][2] != 1:
            raise ValueError('Deck is no longer an unrotated fixed-thickness slab')
        x, y, z = d['loc']
        hx, hy = 625 * d['scale'][0], 625 * d['scale'][1]
        box = (x-hx, y-hy, x+hx, y+hy)
        if overlaps(box, plaza):
            decks.append((*box, z))  # top at instance origin; never the buried terrain
    for f in data['terrain']['triangles']:
        vertices = [data['terrain']['vertices'][i] for i in f]
        if overlaps(bounds(vertices), approach):
            triangles.append(vertices)
    if len(triangles) != 16 or not decks or any(d[4] != -1234.594 for d in decks):
        raise ValueError('Reviewed Kotel zone surface partition changed')
    return decks, triangles


def render():
    decks, triangles = geometry(load())
    lines = ['// Generated by Scripts/generate_crowd_kotel_ground.py; do not edit.',
             '// World centimetres. Exact source surfaces, not fitted native samples.',
             '#pragma once', '#include "CrowdGroundMath.h"', 'namespace CrowdKotelGroundData {']
    for key, (_, digest) in INPUTS.items():
        lines.append(f'inline constexpr const char* {key}Sha256 = "{digest}";')
    lines.append('inline constexpr MikdashCrowdGround::DeckRect Plaza[] = {')
    lines.extend('{' + ','.join(format(v, '.17g') for v in d) + '},' for d in decks)
    lines.append('};\ninline constexpr MikdashCrowdGround::Triangle Approach[] = {')
    for tri in triangles:
        lines.append('{' + ','.join('{' + ','.join(format(v, '.17g') for v in p) + '}' for p in tri) + '},')
    lines.append('};\n}\n')
    return '\n'.join(lines)


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != text:
            raise SystemExit('Crowd Kotel ground header differs')
    else:
        OUTPUT.write_text(text, encoding='utf-8', newline='\n')
    print('Crowd Kotel ground header verified' if args.check else 'Crowd Kotel ground header generated')
