"""Generate the bounded cooked runtime roof table; no Unreal or map writes."""
import argparse
from collections import Counter
import hashlib
import json
import math
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / 'SourceAssets/context-review/LegacyRoofZonesV1/legacy-roof-zones.json'
OUTPUT = ROOT / 'Plugins/MikdashRuntime/Source/MikdashRuntime/Private/LegacyRoofRuntimeData.h'
PLAN_SHA = '4c259972edda978d3163485e1a9f3780d74cc81673b71b3fc5c9edb1dec1137b'
HIDE_SOURCE = ROOT / 'SourceAssets/enclosure-review/precinct-Candidate48.json'
HIDE_SOURCE_SHA = '96d6856cbc506d37f5684321e470a11cc328ef0902afab5bf3ca6fb0632b6dc5'
HIDE_FINGERPRINT = 'ef8a333d75a7daad'


def haram_labels():
    raw = HIDE_SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != HIDE_SOURCE_SHA:
        raise ValueError('Pinned Haram hide source changed')
    labels = set(json.loads(raw)['modernCityRing']['labels'])
    # This absent actor is recorded by the fresh native HideSetV1 verification.
    labels.remove('SM_JerusalemBuildings_Large_07279')
    fingerprint = 1469598103934665603
    for label in sorted(labels):
        for byte in label.encode('utf-8'):
            fingerprint = ((fingerprint ^ byte) * 1099511628211) & 0xffffffffffffffff
    if len(labels) != 48 or '%016x' % fingerprint != HIDE_FINGERPRINT:
        raise ValueError('Haram hide policy does not match native verification')
    return labels


def repartition(plan, labels):
    source, _ = validate(plan)
    rows = [dict(row, zone='precinct' if row['buildingLabel'] in labels else 'kept')
            for row in source]
    owners = sorted({row['buildingLabel'] for row in rows if row['zone'] == 'precinct'})
    if Counter(row['zone'] for row in rows) != {'kept': 5889, 'precinct': 118} or len(owners) != 18:
        raise ValueError('Unexpected Haram roof partition')
    return rows, owners

def validate(plan):
    rows = plan['owners']
    if plan['unresolved'] or plan['status'] != 'offline_partition_ready_native_apply_pending':
        raise ValueError('Unresolved plan')
    if len(rows) != 6007 or [r['sourceIndex'] for r in rows] != list(range(6007)):
        raise ValueError('Source order/count changed')
    if Counter(r['zone'] for r in rows) != {'kept':4744, 'precinct':1263}:
        raise ValueError('Partition count changed')
    membership = {}
    for row in rows:
        label = row['buildingLabel']
        if not label.startswith('SM_JerusalemBuildings_'):
            raise ValueError('Unreviewed owner family')
        if label in membership and membership[label] != row['zone']:
            raise ValueError('An owner cannot belong to both zones')
        membership[label] = row['zone']
        for key in ('tankTranslationCm', 'panelTranslationCm'):
            if len(row[key]) != 3 or not all(math.isfinite(v) for v in row[key]):
                raise ValueError('Nonfinite/invalid translation')
            if any(abs(struct.unpack('<f', struct.pack('<f', v))[0]-v) > .01 for v in row[key]):
                raise ValueError('Float table loses required position precision')
    owners = sorted(label for label, zone in membership.items() if zone == 'precinct')
    if len(owners) != 179:
        raise ValueError('Precinct identity count changed')
    return rows, owners

def render(plan):
    rows, owners = repartition(plan, haram_labels())
    def number(v):
        s = format(struct.unpack('<f',struct.pack('<f',v))[0], '.9g')
        return s + ('f' if '.' in s or 'e' in s else '.0f')
    lines = ['// Generated by Scripts/generate_legacy_roof_runtime.py. Do not edit.', '#pragma once',
        'namespace LegacyRoofRuntimeData {',
        'static constexpr const char* PlanSHA256 = "' + PLAN_SHA + '";',
        'static constexpr const char* HideSourceSHA256 = "' + HIDE_SOURCE_SHA + '";',
        'static constexpr const char* HideFingerprint = "' + HIDE_FINGERPRINT + '";',
        'static constexpr int ExpectedHideCount = 48;',
        'static constexpr int PairCount = 6007, PrecinctCount = 118, KeptCount = 5889;',
        'static constexpr float TranslationCm[PairCount][6] = {']
    for r in rows:
        lines.append('{' + ','.join(number(v) for v in r['tankTranslationCm']+r['panelTranslationCm']) + '},')
    lines += ['};', 'static constexpr const char* PrecinctOwners[] = {']
    lines += ['"' + label + '",' for label in owners]
    lines += ['};', 'struct FPrecinctPair { unsigned short SourceIndex; unsigned short OwnerIndex; };',
              'static constexpr FPrecinctPair PrecinctPairs[PrecinctCount] = {']
    index = {label:i for i,label in enumerate(owners)}
    lines += ['{' + str(r['sourceIndex']) + ',' + str(index[r['buildingLabel']]) + '},'
              for r in rows if r['zone']=='precinct']
    return '\n'.join(lines + ['};', '} // namespace LegacyRoofRuntimeData', ''])

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    raw=PLAN.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=PLAN_SHA:
        raise ValueError('Pinned plan bytes changed')
    output=render(json.loads(raw.decode('utf-8-sig')))
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != output:
            raise ValueError('Generated runtime table stale')
        print('PASS: frozen runtime table exactly matches pinned 6007-pair plan')
    else:
        with OUTPUT.open('w',encoding='utf-8',newline='\n') as stream: stream.write(output)
        print(str(OUTPUT))

if __name__ == '__main__':
    main()
