"""Guarded native placement of the Western Wall Plaza - KotelPlazaV1.

WHAT THIS FINISHES
------------------
The user asked, 9 September 2026:

    "i also want you to restore the old city to its current modern day layout... with kotel
     plaza and then houses up to that point"

The houses half needed nothing. Measured against the 11,437-building city model,
kotel-plaza-manifest.json `buildingCensus` found ZERO buildings whose centroid falls inside
the plaza polygon and 4 with a vertex on its edge, and the modern-restore audit proved they
already come back in MODERN on both maps. That IS the post-1967 layout: the Mughrabi Quarter
was cleared in June 1967 and the OSM data is post-1967.

The plaza half was generated by Scripts/create_kotel_plaza.py and DELIBERATELY NOT PLACED.
kotel-plaza-findings.json says why: the 25 m DEM cannot describe a man-made terrace, so at
the generated deck levels the terrain pierced the plan across 59.8 per cent of its area,
median 2.12 m and up to 4.90 m, and no flat level escaped it.

THAT BLOCKER IS GONE. Scripts/release_precinct_terrain_cut.py -CutApply cut the terrain under
the plaza on 10 September 2026 (note the tile is SM_JerusalemTerrain_07_08 by asset name -
row_col = chunkX_chunkZ - and NOT 08_07, which is what the KotelPlazaV1 manifest and the
hand-off both called it). Its twin lives at
/Game/MikdashV3/KotelPlazaCutV1/SM_JerusalemTerrain_07_08_FutureMountCut_KotelPlazaCut and
its acceptance reads 5.9e-06 cm of terrain above the deck underside over 5,533 stations, with
the surface outside the cut unmoved to 0.00036 cm over 116,577.

So this script places the plan, and then MEASURES THE CLEARANCE OFF THE PLACED DECK rather
than inheriting the cut receipt's number - which is the whole point of the terrain work and
the one number a reader should look at first.

WHAT IS PLACED - and what it is meant to read as
------------------------------------------------
One actor, four HierarchicalInstancedStaticMeshComponents, 1,029 instances, 12,348 triangles,
reusing four PrecinctPlazaV1 modules and two materials that are already imported. NOTHING IS
IMPORTED HERE.

  deck  926  SM_PlazaV1_DeckTile      M_PrecinctPlaza_Paving   the two levels of paving
  step   50  SM_PlazaV1_Step          MI_PrecinctPlaza_Ashlar  the flight between them
  kerb   25  SM_PlazaV1_Kerb          MI_PrecinctPlaza_Ashlar  4 mechitza + 21 parapet
  band   28  SM_PlazaV1_RetainingBand MI_PrecinctPlaza_Ashlar  retaining down to grade

This is a real place and people will recognise it, so the reading matters more than the
geometry. What the plan actually describes:

  * A LOWER PRAYER PLAZA at the wall, 40 m deep, at 735.65 m a.s.l.
  * THE MECHITZA across it, 180 cm of kerb turned perpendicular to the wall and set 0.62 of
    the way along the wall from its north end, running from the 200 cm wall guard out to the
    flight. North of it is the men's section, south of it the women's. That division is the
    single thing a viewer will check first, and it is four instances.
  * THE FLIGHT between the levels: 10 risers of the existing SM_PlazaV1_Step, 25 cm rise and
    100 cm tread, five modules wide, running parallel to the wall.
  * THE RAISED UPPER PLAZA behind, at 738.15 m a.s.l., 2.5 m above the prayer plaza.
  * A 110 cm PARAPET where the deck stands more than a metre above grade, and retaining bands
    down to grade under it.

WHAT IS NOT BUILT - said plainly, not half-built
------------------------------------------------
  * Wilson's Arch. A vaulted hall under the buildings at the north end; interior
    architecture, not a plaza surface, and none of it is modelled.
  * The Mughrabi ramp at the south end. The Mughrabi Gate building (OSM 291836692) is in the
    model; the ramp is not.
  * Prayer furniture: shtenders, book cases, partition rails, chairs.
  * The security plaza, its entrances and its screening at the west.
  * Lighting of any kind.
  * NO VISUAL ACCEPTANCE. Nobody has looked at any of this in a frame.
  * The VOID under the fill. The cut clamped terrain DOWN to the deck underside where it
    stood above; where the hillside already fell away the deck simply flies over it, up to
    4.35 m at the worst station, with retaining bands only at the perimeter. The clearance
    histogram in the receipt reports that honestly instead of averaging it away.

WHICH COORDINATE FRAME - and why it is the identity on both maps
----------------------------------------------------------------
Scripts/map_targets.py exists because Candidate48 is Main50 under
p_candidate = 0.96 * p_main50 + (-248, 0, 0), and anything placed on the candidate at
authored coordinates is 4 per cent oversized and 2.48 m out. But that similarity was applied
to the 2,633 ARCHITECTURE actors only. The metric city and the 256 DEM ground tiles were
never rescaled and stand at identical coordinates on both maps.

The Kotel plaza stands on the ground, not on the architecture:

  * its footprint is OSM way 26492734 carried through the export_buildings.py alignment that
    placed the whole metric city, the same alignment as the 11,437 buildings around it;
  * its deck levels are DEM percentiles;
  * the terrain cut it sits on is ONE asset shared by both maps - Main50 and Candidate48 both
    cut SM_JerusalemTerrain_07_08 over the SAME 146 merged rectangles and read back the SAME
    5,533 stations and the SAME 5.859375278305379e-06 cm. kotel_job() in
    release_precinct_terrain_cut.py takes no target argument at all.

So the plaza is placed AT IDENTITY on both maps, and that is not taken on trust. Every run
records, into its receipt:

  * `groundFrame` - the world AABB of the terrain tile actor under the plaza and of the Kotel
    building mesh actor. Identical between the two receipts means the ground did not move;
  * `architectureFrame` - map_targets.prove_placement() SOLVED off the live level against
    SourceAssets/architecture-manifest.json. On Candidate48 it measures 0.96 / (-248, 0, 0)
    and on Main50 the identity. It is recorded to show the frame this pass deliberately did
    NOT ride, and it doubles as proof the run loaded the map it thinks it did.

STATE: the plaza is a MODERN feature and must not stand in YECHEZKEL
---------------------------------------------------------------------
The actor is tagged `KotelPlazaCutTwin`, which is already in AMikdashEnclosure's
HideWhileWallStandsTags (MikdashEnclosure.cpp:204) - hidden while the Yechezkel precinct
stands, shown in MODERN and OVERLAY. It shares that tag with the terrain twin it stands on
DELIBERATELY: the deck and the ground it was cut into must appear and disappear together, and
one tag makes it impossible for them to disagree. It also carries `KotelPlazaV1` as its own
identity, which no phase list mentions.

It is saved HIDDEN with collision off, which is the YECHEZKEL-correct state on disk and
exactly how release_precinct_terrain_cut.py left the twin. ApplyStateTaggedActors turns both
back on together when MODERN is entered in a game world.

The actor cannot be caught by the building hide path: AMikdashEnclosure::BuildingIdentityLabel
returns an empty label for a HISM-only actor, and GatherModernBuildings skips empty labels.

MODES (one per run)
-------------------
  -PlazaApply    checkpoint, place, save, reopen, read back, measure.
  -PlazaVerify   reopen and measure. Saves nothing; refuses if the map bytes move.
  -PlazaRevert=<apply receipt>   destroy what that run placed, save, reopen, confirm.
  -PlazaRebuild  with -PlazaApply: destroy an existing plaza actor and rebuild it.

TARGET (map_targets.py; Main50 is the default, retargeting is opt-in)
  -Candidate48   the cook map and the configured GameDefaultMap. RUN THIS ONE FIRST.
  -Main50        the legacy authoring map.

Commandlet invocation - nullrhi only, serial, never while another native job runs:

  "C:\\Program Files\\Epic Games\\UE_5.8\\Engine\\Binaries\\Win64\\UnrealEditor-Cmd.exe"
      "C:\\Mikdash\\Working-5.8\\MikdashCourtyardV3\\MikdashCourtyardV3.uproject"
      -run=pythonscript
      -script="C:/Mikdash/Working-5.8/MikdashCourtyardV3/Scripts/release_kotel_plaza.py"
      -Candidate48 -PlazaApply
      -EnablePlugins=GeometryScripting -unattended -nullrhi
      -abslog="C:/Mikdash/Working-5.8/KotelPlaza-01.log"

GeometryScripting is required: the clearance measurement reads the terrain twin's SOURCE
MODEL triangles, the same way the cut that made it did, rather than line-tracing against
collision that is switched off on a hidden actor.

Offline, with no engine:
  python Scripts/release_kotel_plaza.py                  the plan and every hash it pins
  python Scripts/release_kotel_plaza.py --revert=<receipt> [--dry-run]
      byte-exact restore of the .umap from that run's ReviewCheckpoints copy, via
      map_targets.restore_checkpoint.

UE 5.8 PYTHON TRAPS HONOURED HERE (AGENTS.md, and the receipts that paid for them)
----------------------------------------------------------------------------------
  * AActor.add_component_by_class is NOT exposed to Python; the SubobjectDataSubsystem path
    is used and component ownership is verified three ways (release_city_detail.py).
  * spawn_actor_from_object returns None in commandlets; actors are spawned from a class.
  * unreal.Transform's positional order is (rotation, translation, scale), which is not the
    order a reader expects. Transforms are built by keyword after a probe, and every claim is
    a numeric readback - a silently swapped location and rotation survives a count check.
  * unreal.Rotator needs explicit pitch/yaw/roll keywords.
  * Mobility lives on the component, not the actor.
  * 5.8 setters return False even when they worked; nothing is trusted until it is read back
    off the REOPENED map.
"""
import hashlib
import json
import math
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(r'C:\Mikdash\Working-5.8\MikdashCourtyardV3')
SCRIPTS = ROOT / 'Scripts'
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import map_targets                                                       # noqa: E402
import release_precinct_terrain_cut as cut                               # noqa: E402
import create_kotel_plaza as gen                                         # noqa: E402

FOLDER = ROOT / 'SourceAssets/context-review/KotelPlazaV1'
MANIFEST_PATH = FOLDER / 'kotel-plaza-manifest.json'
PLAN_PATH = FOLDER / 'kotel-plaza-plan.json'
PLAZA_MODULE_MANIFEST = ROOT / 'SourceAssets/enclosure-review/plaza-manifest.json'
CHECKPOINT_ROOT = Path(r'C:\Mikdash\Working-5.8\ReviewCheckpoints')

SCRIPT_TOKEN = 'release_kotel_plaza.py'
ACTOR_LABEL = 'RELEASE_KotelPlaza'
ACTOR_FOLDER = 'Release/KotelPlazaV1'
IDENTITY_TAG = 'KotelPlazaV1'
# Already in AMikdashEnclosure::HideWhileWallStandsTags (MikdashEnclosure.cpp:204): hidden
# while the Yechezkel precinct stands, shown in MODERN and OVERLAY. Shared with the terrain
# twin on purpose - see the module docstring.
STATE_TAG = 'KotelPlazaCutTwin'

# The terrain the plaza stands on in MODERN. Cut by release_precinct_terrain_cut.py.
TERRAIN_TILE = 'SM_JerusalemTerrain_07_08'
TERRAIN_TWIN = ('/Game/MikdashV3/KotelPlazaCutV1/'
                'SM_JerusalemTerrain_07_08_FutureMountCut_KotelPlazaCut')
TERRAIN_TWIN_ACTOR_LABEL = 'RELEASE_KotelPlazaCut_07_08'
# The Kotel itself. 734.0 - 754.0 m a.s.l., 200 cm no-edit guard, NEVER TOUCHED.
KOTEL_MESH = '/Game/MikdashV3/JerusalemContext/Buildings/SM_JerusalemBuildings_Grid_N002_P001'

# The Main50 ground fingerprint Scripts/candidate_placement_proof.py measured off the live
# level: the 256 DEM tiles' world AABBs. Identity placement on Candidate48 is only correct if
# the terrain there really is the same terrain, and this is the only thing in the project that
# proves it. The *Cut twins are excluded on both sides because the PRECINCT square they are cut
# to is itself 4 per cent smaller on the candidate - the Kotel cut is not, but the exclusion is
# kept identical to release_vegetation.py's so the two comparisons mean the same thing.
GROUND_REFERENCE = ROOT / 'SourceAssets/scale-review/ground-fingerprint-Main50.json'
GROUND_PARITY_TOLERANCE_CM = 0.5
CUT_TWIN_TOKENS = ('PrecinctCut', 'KotelPlazaCut', 'FutureMountCut')

# Same 100 cm step the earthwork measurement and the terrain cut both used, so this number
# and theirs are comparable.
SAMPLE_SPACING_CM = 100.0
# StaticMesh source models are float32; at |x| ~ 23,000 cm a coordinate reads back up to
# ~0.002 cm either side. The cut used 0.05 cm for the same reason and so does this.
TOLERANCE_CM = 0.05
INSTANCE_TOLERANCE_CM = 0.01

MODE_FLAGS = {'-plazaapply': 'apply', '-plazaverify': 'verify', '-plazarevert': 'revert'}


def sha256_of(path):
    digest = hashlib.sha256()
    with Path(path).open('rb') as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b''):
            digest.update(chunk)
    return digest.hexdigest()


def disk_path(asset_path, extension='uasset'):
    if not asset_path.startswith('/Game/'):
        raise ValueError('Only /Game/ assets are expected: ' + asset_path)
    return ROOT / 'Content' / (asset_path[6:] + '.' + extension)


def stamp_now():
    return datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')


# =====================================================================================
# Pure: the plan, its hashes and the polygon it is clipped to. No engine.
# =====================================================================================
def plaza_polygon():
    """The 31 sourced vertices of OSM way 26492734, from the design file the generator used.

    NOT re-derived. The polygon is read from the SAME `protected` entry of
    mount-platform-design.json that create_kotel_plaza.load_sources() reads, and that file's
    SHA-256 is checked against the one kotel-plaza-manifest.json pinned when the plan was
    generated. Re-deriving it from jerusalem.json would re-apply an alignment that
    export_buildings.py already baked once, which is the exact mistake the manifest's
    `source.alignment` note warns about.
    """
    design = json.loads(gen.DESIGN.read_text(encoding='utf-8-sig'))
    entry = next((e for e in design['protected'] if e.get('osmId') == gen.PLAZA_OSM_ID), None)
    if entry is None:
        raise RuntimeError('mount-platform-design.json carries no OSM way %d' % gen.PLAZA_OSM_ID)
    polygon = [(float(x), float(y)) for x, y in entry['nativeXYcm']]
    if polygon[0] == polygon[-1]:
        polygon = polygon[:-1]
    return polygon


def offline_plan():
    """Everything this pass will do, and every hash it stands on, with no engine running."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding='utf-8-sig'))
    plan = json.loads(PLAN_PATH.read_text(encoding='utf-8-sig'))
    failures = []

    plan_sha = sha256_of(PLAN_PATH)
    if plan_sha != manifest['planSha256']:
        failures.append('kotel-plaza-plan.json hashes %s, the manifest pins %s'
                        % (plan_sha, manifest['planSha256']))
    design_sha = sha256_of(gen.DESIGN)
    if design_sha != manifest['source']['designSha256']:
        failures.append('mount-platform-design.json hashes %s, the manifest pins %s'
                        % (design_sha, manifest['source']['designSha256']))

    polygon = plaza_polygon()
    polygon_area_cm2 = abs(gen.polygon_area(polygon))
    if abs(polygon_area_cm2 / 1e4 - manifest['sourced']['plazaAreaM2']) > 0.05:
        failures.append('The design polygon measures %.2f m2, the manifest says %.2f'
                        % (polygon_area_cm2 / 1e4, manifest['sourced']['plazaAreaM2']))

    modules = json.loads(PLAZA_MODULE_MANIFEST.read_text(encoding='utf-8-sig'))
    by_name = {m['name']: m for m in modules['meshes']}

    components = []
    triangles = 0
    for spec in manifest['components']:
        rows = plan[spec['key']]
        if len(rows) != spec['instances']:
            failures.append('%s: the plan holds %d instances, the manifest says %d'
                            % (spec['key'], len(rows), spec['instances']))
        name = spec['mesh'].rsplit('/', 1)[-1]
        module = by_name.get(name)
        if module is None:
            failures.append('plaza-manifest.json has no module %s' % name)
            continue
        if not disk_path(spec['mesh']).is_file():
            failures.append('Mesh missing on disk: ' + spec['mesh'])
        if not disk_path(spec['material']).is_file():
            failures.append('Material missing on disk: ' + spec['material'])
        for row in rows:
            if abs(row['rot'][0]) > 1e-9 or abs(row['rot'][1]) > 1e-9:
                failures.append('%s: an instance carries roll or pitch; only yaw is planned'
                                % spec['key'])
                break
        triangles += module['triangles'] * len(rows)
        components.append(dict(key=spec['key'], mesh=spec['mesh'], material=spec['material'],
                               instances=len(rows), castShadow=spec['castShadow'],
                               meshTriangles=module['triangles'],
                               canonicalBoundsCm=module['canonicalBoundsCm'],
                               note=spec['note']))
    if triangles != manifest['triangleTotal']:
        failures.append('Triangles total %d, the manifest says %d'
                        % (triangles, manifest['triangleTotal']))

    # The deck: cells, levels and the slab underside the terrain was cut to. Re-derived from
    # the plan rows exactly as release_precinct_terrain_cut.kotel_job() derived them, so this
    # pass and the cut cannot disagree about where the underside is.
    deck_module = by_name['SM_PlazaV1_DeckTile']['canonicalBoundsCm']
    half_x = 0.5 * (deck_module['max'][0] - deck_module['min'][0])
    half_y = 0.5 * (deck_module['max'][1] - deck_module['min'][1])
    thickness = deck_module['max'][2] - deck_module['min'][2]
    if abs(deck_module['max'][2]) > 1e-9:
        failures.append('The deck tile origin is not on the deck plane')
    levels = {}
    deck_area_cm2 = 0.0
    for row in plan['deck']:
        if abs(row['scale'][2] - 1.0) > 1e-9:
            failures.append('A deck cell is scaled in Z; the slab thickness would move')
            break
        levels[round(row['loc'][2], 3)] = round(row['loc'][2] - thickness, 3)
        deck_area_cm2 += (2 * half_x * row['scale'][0]) * (2 * half_y * row['scale'][1])
    for key in ('lowerDeckZCm', 'upperDeckZCm'):
        if round(manifest['derived'][key], 3) not in levels:
            failures.append('The plan carries no deck cell at the manifest %s' % key)

    twin_present = disk_path(TERRAIN_TWIN).is_file()
    if not twin_present:
        failures.append('The terrain cut twin is missing: ' + TERRAIN_TWIN)

    return dict(
        script=SCRIPT_TOKEN,
        scriptSha256=sha256_of(Path(__file__)),
        planSha256=plan_sha,
        manifestSha256=sha256_of(MANIFEST_PATH),
        designSha256=design_sha,
        plazaModuleManifestSha256=sha256_of(PLAZA_MODULE_MANIFEST),
        generatorSha256=sha256_of(SCRIPTS / 'create_kotel_plaza.py'),
        generatorSha256InManifest=manifest['generatorSha256'],
        osmWay=manifest['source']['plazaOsmId'],
        polygonVertices=len(polygon),
        polygonAreaM2=round(polygon_area_cm2 / 1e4, 3),
        polygonBboxCm=manifest['sourced']['plazaBboxCm'],
        deckThicknessCm=thickness,
        deckLevelTopToUndersideZCm=levels,
        deckLevelsMasl=dict(lower=manifest['derived']['lowerDeckMasl'],
                            upper=manifest['derived']['upperDeckMasl']),
        deckCells=len(plan['deck']),
        deckCellsDroppedForWallGuard=manifest['derived']['deckCellsDroppedForWallGuard'],
        deckAreaM2=round(deck_area_cm2 / 1e4, 3),
        deckAreaVersusPolygonPercent=round(100.0 * deck_area_cm2 / polygon_area_cm2, 3),
        components=components,
        instanceTotal=sum(c['instances'] for c in components),
        triangleTotal=triangles,
        terrainTile=TERRAIN_TILE,
        terrainTwin=TERRAIN_TWIN,
        terrainTwinPresent=twin_present,
        terrainTwinSha256=sha256_of(disk_path(TERRAIN_TWIN)) if twin_present else None,
        wallGuardCm=manifest['sourced']['wallGuardCm'],
        kotelMeshMasl=[manifest['earthwork']['kotelMeshInLevel']['baseMasl'],
                       manifest['earthwork']['kotelMeshInLevel']['topMasl']],
        reading=dict(
            mechitza='4 kerb instances at 180 cm, perpendicular to the wall, 0.62 along it '
                     'from the north end: men north, women south.',
            lowerPlaza='%d deck cells at %.2f m a.s.l., 40 m deep at the wall.'
                       % (sum(1 for r in plan['deck']
                              if round(r['loc'][2], 3) == round(manifest['derived']['lowerDeckZCm'], 3)),
                          manifest['derived']['lowerDeckMasl']),
            upperPlaza='%d deck cells at %.2f m a.s.l., 2.50 m above the prayer plaza.'
                       % (sum(1 for r in plan['deck']
                              if round(r['loc'][2], 3) == round(manifest['derived']['upperDeckZCm'], 3)),
                          manifest['derived']['upperDeckMasl']),
            flight='%d SM_PlazaV1_Step instances, %d risers of %g cm across %d modules.'
                   % (len(plan['step']), manifest['derived']['risers'],
                      float(manifest['authored'].get('riserCm', 25.0)),
                      len(plan['step']) // max(1, manifest['derived']['risers'])),
            parapet='%d kerb instances at 110 cm where the deck stands over 1 m above grade.'
                    % sum(1 for r in plan['kerb'] if r.get('role') == 'parapet'),
            retaining='%d retaining bands, 250 cm each, never scaled in Z.' % len(plan['band'])),
        notBuilt=manifest['notBuilt'],
        limitations=manifest['limitations'] + [
            'The void under the fill. The cut lowered terrain that stood ABOVE the deck; where '
            'the hillside already fell away the deck flies over it, with retaining bands only '
            'at the perimeter. The clearance histogram reports that rather than hiding it.',
            'No navmesh contribution: can_ever_affect_navigation is False on every component, '
            'so nothing here is walkable to the crowd system. Collision blocks a player pawn '
            'only, and only once MODERN turns the actor on in a game world.',
            'NO VISUAL ACCEPTANCE. Nobody has looked at the placed plaza in a frame.'],
        failures=failures,
        offlineOk=not failures)


# =====================================================================================
# Native
# =====================================================================================
class Native(object):
    def __init__(self, ue, target_key, mode, stamp):
        self.ue = ue
        self.target_key = target_key
        self.config = map_targets.target_config(target_key)
        self.mode = mode
        self.stamp = stamp
        for name in ('GeometryScript_AssetUtils', 'GeometryScript_MeshQueries'):
            if not hasattr(ue, name):
                raise RuntimeError('Launch with -EnablePlugins=GeometryScripting: ' + name)
        self.query = ue.GeometryScript_MeshQueries
        self.asset_utils = ue.GeometryScript_AssetUtils
        self.editor = ue.get_editor_subsystem(ue.UnrealEditorSubsystem)
        self.assets = ue.get_editor_subsystem(ue.EditorAssetSubsystem)
        self.actors = ue.get_editor_subsystem(ue.EditorActorSubsystem)
        self.levels = ue.get_editor_subsystem(ue.LevelEditorSubsystem)
        self.receipt = {}
        self.receipt_path = None
        self.transform_path = None

    def write_receipt(self):
        self.receipt_path.parent.mkdir(parents=True, exist_ok=True)
        self.receipt_path.write_text(
            json.dumps(self.receipt, indent=2, sort_keys=False) + '\n', encoding='utf-8')

    # -- level census ------------------------------------------------------
    def mesh_of(self, actor):
        component = actor.get_component_by_class(self.ue.StaticMeshComponent)
        if component is None:
            return None, None
        return component, component.get_editor_property('static_mesh')

    def snapshot_rows(self):
        """One row per level actor: label, the mesh assets it renders, and its world AABB.

        The shape map_targets.prove_placement() and terrain_fingerprint() both expect.
        """
        ue = self.ue
        rows = []
        for actor in self.actors.get_all_level_actors():
            meshes = []
            for component in actor.get_components_by_class(ue.StaticMeshComponent):
                mesh = component.get_editor_property('static_mesh')
                if mesh is not None:
                    meshes.append(mesh.get_path_name())
            if not meshes:
                continue
            origin, extent = actor.get_actor_bounds(False)
            rows.append(dict(
                label=actor.get_actor_label(), name=actor.get_name(), meshes=meshes,
                bounds={'min': [origin.x - extent.x, origin.y - extent.y, origin.z - extent.z],
                        'max': [origin.x + extent.x, origin.y + extent.y, origin.z + extent.z]}))
        return rows

    def ground_frame(self, rows):
        """The two things the plaza is registered against, in world centimetres.

        Identical between the Candidate48 and Main50 receipts is the measurement that says
        the identity is the right transform for this pass.
        """
        wanted = {}
        for row in rows:
            names = [m.rsplit('/', 1)[-1].split('.')[0] for m in row['meshes']]
            if TERRAIN_TILE in names or (TERRAIN_TILE + '_FutureMountCut') in names:
                wanted.setdefault('terrainTileActor', []).append(
                    dict(label=row['label'], meshes=row['meshes'],
                         bounds={k: [round(v, 4) for v in row['bounds'][k]]
                                 for k in ('min', 'max')}))
            if KOTEL_MESH.rsplit('/', 1)[-1] in names:
                wanted.setdefault('kotelBuildingActor', []).append(
                    dict(label=row['label'], meshes=row['meshes'],
                         bounds={k: [round(v, 4) for v in row['bounds'][k]]
                                 for k in ('min', 'max')}))
        return wanted

    def prove_ground(self, rows):
        """The ground has not moved - which is the entire licence for identity placement.

        Every SM_JerusalemTerrain_* actor's live world AABB against the same tile read off the
        live Main50 level by Scripts/candidate_placement_proof.py. Not believed: measured.
        """
        live = {k: v for k, v in map_targets.terrain_fingerprint(rows).items()
                if not any(token in k for token in CUT_TWIN_TOKENS)}
        report = dict(target=self.config['key'], liveGroundTiles=len(live),
                      reference=str(GROUND_REFERENCE),
                      toleranceCm=GROUND_PARITY_TOLERANCE_CM,
                      cutTwinTokensExcluded=list(CUT_TWIN_TOKENS))
        if self.target_key == map_targets.AUTHORING_TARGET:
            report['status'] = 'authoring_frame_is_its_own_reference'
            return report
        if not GROUND_REFERENCE.is_file():
            raise RuntimeError(
                'No Main50 ground fingerprint at %s. Placing on %s at identity coordinates is '
                'only correct if the terrain is proved to be the same terrain.'
                % (GROUND_REFERENCE, self.config['key']))
        reference = json.loads(GROUND_REFERENCE.read_text(encoding='utf-8-sig'))
        comparison = map_targets.compare_fingerprints(reference['tiles'], live)
        report.update(comparison)
        report['referenceStamp'] = reference.get('stamp')
        if comparison['matchedLabels'] < 200:
            raise RuntimeError('Only %d ground tiles matched the Main50 fingerprint'
                               % comparison['matchedLabels'])
        if comparison['worstBoundsErrorCm'] > GROUND_PARITY_TOLERANCE_CM:
            raise RuntimeError('The ground is NOT the same terrain on %s: worst tile AABB '
                               'differs by %.4f cm on %s. Identity placement would be wrong.'
                               % (self.config['key'], comparison['worstBoundsErrorCm'],
                                  comparison['worstLabel']))
        report['status'] = 'ground_is_identical_to_main50_identity_placement_is_correct'
        return report

    # -- placement ---------------------------------------------------------
    def make_transform(self, row):
        ue = self.ue
        location = ue.Vector(float(row['loc'][0]), float(row['loc'][1]), float(row['loc'][2]))
        rotation = ue.Rotator(pitch=float(row['rot'][1]), yaw=float(row['rot'][2]),
                              roll=float(row['rot'][0]))
        scale = ue.Vector(float(row['scale'][0]), float(row['scale'][1]), float(row['scale'][2]))
        if self.transform_path is None:
            self.transform_path = self._probe_transform_path(location, rotation, scale)
        if self.transform_path == 'keyword_rotation_translation_scale':
            return ue.Transform(rotation=rotation, translation=location, scale=scale)
        transform = ue.Transform()
        transform.set_editor_property('translation', location)
        transform.set_editor_property('rotation', rotation.quaternion())
        transform.set_editor_property('scale3d', scale)
        return transform

    def _probe_transform_path(self, location, rotation, scale):
        """unreal.Transform's POSITIONAL order is (rotation, translation, scale). A run that
        assumes (translation, rotation, scale) places 1,029 instances at the origin and still
        passes an instance-count check, so the construction path is probed and recorded."""
        ue = self.ue
        try:
            probe = ue.Transform(rotation=rotation, translation=location, scale=scale)
            got = probe.get_editor_property('translation')
            if (abs(got.x - location.x) < 1e-3 and abs(got.y - location.y) < 1e-3
                    and abs(got.z - location.z) < 1e-3):
                self.receipt['transformConstruction'] = 'keyword_rotation_translation_scale'
                return 'keyword_rotation_translation_scale'
        except Exception as error:                                           # noqa: BLE001
            self.receipt.setdefault('limitations', []).append(
                'unreal.Transform keyword construction unavailable (%r)' % (error,))
        self.receipt['transformConstruction'] = 'set_editor_property'
        return 'set_editor_property'

    def new_hism(self, actor):
        """Instance-owned HISM on a plain editor actor, via the editor subobject path.

        UE 5.8 does not expose AActor::AddComponentByClass to Python (it raises
        AttributeError - the failure that cost release_city_detail.py its first run), and
        constructing the component with outer=actor makes one the level never owns.
        Ownership is verified three ways before an instance is added.
        """
        ue = self.ue
        subsystem = ue.get_engine_subsystem(ue.SubobjectDataSubsystem)
        library = ue.SubobjectDataBlueprintFunctionLibrary
        handles = subsystem.k2_gather_subobject_data_for_instance(actor)
        parent = next((h for h in handles
                       if library.get_associated_object(library.get_data(h)) == actor), None)
        if parent is None:
            raise RuntimeError('Editor actor subobject handle missing')
        params = ue.AddNewSubobjectParams(
            parent_handle=parent,
            new_class=ue.HierarchicalInstancedStaticMeshComponent,
            blueprint_context=None, conform_transform_to_parent=True)
        handle, reason = subsystem.add_new_subobject(params)
        if not library.is_handle_valid(handle):
            raise RuntimeError('Persistent HISM creation failed: ' + str(reason))
        data = library.get_data(handle)
        component = library.get_associated_object(data)
        if not isinstance(component, ue.HierarchicalInstancedStaticMeshComponent):
            raise RuntimeError('Subobject is a %s, not a HISM' % type(component).__name__)
        if component.get_owner() != actor or not library.is_instanced_component(data):
            raise RuntimeError('HISM ownership / instance creation not verified')
        if component not in actor.get_components_by_class(
                ue.HierarchicalInstancedStaticMeshComponent):
            raise RuntimeError('HISM absent from the actor component readback')
        return component

    def add_instances(self, component, transforms):
        try:
            component.add_instances(transforms, False, True, False)
            self.receipt.setdefault('instanceApi', 'add_instances(world_space=True)')
        except TypeError:
            component.add_instances(transforms, False)
            self.receipt.setdefault('instanceApi', 'add_instances(local, actor at identity)')

    def plaza_actors(self):
        return [a for a in self.actors.get_all_level_actors()
                if a.get_actor_label() == ACTOR_LABEL
                or IDENTITY_TAG in [str(t) for t in a.get_editor_property('tags')]]

    def build(self, plan, components):
        ue = self.ue
        actor = self.actors.spawn_actor_from_class(
            ue.Actor, ue.Vector(0.0, 0.0, 0.0), ue.Rotator(pitch=0.0, yaw=0.0, roll=0.0))
        if actor is None:
            raise RuntimeError('spawn_actor_from_class returned None')
        actor.set_actor_label(ACTOR_LABEL)
        actor.set_folder_path(ACTOR_FOLDER)
        actor.set_editor_property('tags', [ue.Name(IDENTITY_TAG), ue.Name(STATE_TAG)])
        placed = []
        try:
            for spec in components:
                rows = plan[spec['key']]
                mesh = ue.load_asset(spec['mesh'])
                if not isinstance(mesh, ue.StaticMesh):
                    raise RuntimeError('Missing mesh ' + spec['mesh'])
                material = ue.load_asset(spec['material'])
                if material is None:
                    raise RuntimeError('Missing material ' + spec['material'])
                component = self.new_hism(actor)
                component.set_editor_property('static_mesh', mesh)
                component.set_mobility(ue.ComponentMobility.STATIC)
                component.set_material(0, material)
                component.set_editor_property('cast_shadow', bool(spec['castShadow']))
                # Walkable in MODERN, and nothing else. Navigation is left off: a hidden
                # actor that feeds the navmesh would change the map's built nav data as a
                # side effect of this pass, which is not what was asked for.
                component.set_collision_profile_name('BlockAll')
                component.set_editor_property('can_ever_affect_navigation', False)
                transforms = [self.make_transform(row) for row in rows]
                self.add_instances(component, transforms)
                count = int(component.get_instance_count())
                if count != len(rows):
                    raise RuntimeError('%s: planned %d instances, the component reports %d'
                                       % (spec['key'], len(rows), count))
                placed.append(dict(key=spec['key'], component=component.get_name(),
                                   mesh=spec['mesh'], material=spec['material'],
                                   planned=len(rows), placed=count,
                                   castShadow=bool(spec['castShadow']),
                                   collisionProfile=str(
                                       component.get_collision_profile_name())))
                del transforms
        except Exception:
            self.actors.destroy_actor(actor)
            raise
        # The YECHEZKEL-correct state on disk, and exactly how the terrain twin under it was
        # left: hidden, collision off. ApplyStateTaggedActors turns both on together in
        # MODERN, in a game world.
        actor.set_actor_hidden_in_game(True)
        actor.set_actor_enable_collision(False)
        return actor, placed

    # -- terrain -----------------------------------------------------------
    def extract(self, mesh):
        """The SOURCE MODEL triangles of a static mesh, the way the cut that built the twin
        read them. Not a line trace: the twin actor's collision is deliberately off."""
        ue = self.ue
        dynamic = ue.DynamicMesh()
        options = ue.GeometryScriptCopyMeshFromAssetOptions()
        options.set_editor_property('apply_build_settings', False)
        options.set_editor_property('request_tangents', False)
        options.set_editor_property('use_build_scale', False)
        lod = ue.GeometryScriptMeshReadLOD()
        lod.set_editor_property('lod_type', ue.GeometryScriptLODType.SOURCE_MODEL)
        lod.set_editor_property('lod_index', 0)
        result = self.asset_utils.copy_mesh_from_static_mesh_v2(mesh, dynamic, options, lod)
        if ue.GeometryScriptOutcomePins.SUCCESS not in result:
            raise RuntimeError('Source-mesh extraction failed for ' + mesh.get_path_name())
        faces = []
        for tid in range(dynamic.get_triangle_count()):
            positions = [[v.x, v.y, v.z]
                         for v in self.query.get_triangle_positions(dynamic, tid)
                         if isinstance(v, ue.Vector)]
            if len(positions) != 3:
                raise RuntimeError('Incomplete triangle readback on ' + mesh.get_path_name())
            faces.append(positions)
        return faces

    def terrain_over_plaza(self, bbox):
        """Every terrain actor whose mesh bounds overlap the plaza footprint, with what it
        renders and whether it is visible in the state saved on disk."""
        ue = self.ue
        rows = []
        for actor in self.actors.get_all_level_actors():
            component, mesh = self.mesh_of(actor)
            if mesh is None or not mesh.get_name().startswith('SM_JerusalemTerrain_'):
                continue
            bounds = mesh.get_bounds()
            origin, extent = bounds.origin, bounds.box_extent
            if (origin.x + extent.x <= bbox[0] or origin.x - extent.x >= bbox[2]
                    or origin.y + extent.y <= bbox[1] or origin.y - extent.y >= bbox[3]):
                continue
            rows.append(dict(actor=actor.get_name(), label=actor.get_actor_label(),
                             mesh=mesh.get_name(),
                             meshPath=mesh.get_path_name().split('.')[0],
                             hiddenInGame=bool(actor.get_editor_property('hidden')),
                             collision=bool(actor.get_actor_enable_collision()),
                             tags=[str(t) for t in actor.get_editor_property('tags')]))
        return rows


def read_back(native, plan, components):
    """Every claim, off the REOPENED map: which actor, which components, how many instances
    each, and a numeric transform sample of each against the plan it was built from."""
    ue = native.ue
    matches = native.plaza_actors()
    if len(matches) != 1:
        raise RuntimeError('Expected exactly one %s actor after reopen, found %d'
                           % (ACTOR_LABEL, len(matches)))
    actor = matches[0]
    tags = [str(t) for t in actor.get_editor_property('tags')]
    hisms = list(actor.get_components_by_class(ue.HierarchicalInstancedStaticMeshComponent))
    by_mesh = {}
    for component in hisms:
        mesh = component.get_editor_property('static_mesh')
        by_mesh[mesh.get_path_name().split('.')[0] if mesh else None] = component

    rows = []
    deck_cells = None
    for spec in components:
        component = by_mesh.get(spec['mesh'])
        if component is None:
            raise RuntimeError('No component renders %s after reopen' % spec['mesh'])
        planned = plan[spec['key']]
        count = int(component.get_instance_count())
        material = component.get_material(0)
        worst = 0.0
        worst_scale = 0.0
        worst_yaw = 0.0
        cells = []
        for index in range(count):
            transform = component.get_instance_transform(index, True)
            location = transform.get_editor_property('translation')
            scale = transform.get_editor_property('scale3d')
            rotator = transform.get_editor_property('rotation').rotator()
            row = planned[index]
            worst = max(worst, abs(location.x - row['loc'][0]), abs(location.y - row['loc'][1]),
                        abs(location.z - row['loc'][2]))
            worst_scale = max(worst_scale, abs(scale.x - row['scale'][0]),
                              abs(scale.y - row['scale'][1]), abs(scale.z - row['scale'][2]))
            worst_yaw = max(worst_yaw,
                            abs(((float(rotator.yaw) - row['rot'][2]) + 180.0) % 360.0 - 180.0))
            if spec['key'] == 'deck':
                cells.append((location.x, location.y, location.z, scale.x, scale.y, scale.z))
        if count != len(planned):
            raise RuntimeError('%s: %d instances after reopen, the plan holds %d'
                               % (spec['key'], count, len(planned)))
        if worst > INSTANCE_TOLERANCE_CM or worst_scale > 1e-3 or worst_yaw > 0.05:
            raise RuntimeError('%s read back off the plan by %.4f cm / %.5f scale / %.4f deg'
                               % (spec['key'], worst, worst_scale, worst_yaw))
        if spec['key'] == 'deck':
            deck_cells = cells
        rows.append(dict(key=spec['key'], component=component.get_name(),
                         mesh=spec['mesh'],
                         meshAfterReopen=(component.get_editor_property('static_mesh')
                                          .get_path_name().split('.')[0]),
                         material=spec['material'],
                         materialAfterReopen=(material.get_path_name().split('.')[0]
                                              if material else None),
                         materialMatches=bool(material is not None
                                              and material.get_path_name().split('.')[0]
                                              == spec['material']),
                         planned=len(planned), placed=count,
                         allInstancesChecked=count,
                         worstLocationErrorCm=round(worst, 6),
                         worstScaleError=round(worst_scale, 8),
                         worstYawErrorDeg=round(worst_yaw, 6),
                         castShadow=bool(component.get_editor_property('cast_shadow')),
                         collisionProfile=str(component.get_collision_profile_name()),
                         affectsNavigation=bool(
                             component.get_editor_property('can_ever_affect_navigation'))))
    return dict(actor=actor.get_name(), actorLabel=actor.get_actor_label(),
                folderPath=str(actor.get_folder_path()),
                tags=tags,
                identityTagPresent=IDENTITY_TAG in tags,
                stateTagPresent=STATE_TAG in tags,
                hiddenInGameOnDisk=bool(actor.get_editor_property('hidden')),
                collisionOnDisk=bool(actor.get_actor_enable_collision()),
                componentCount=len(hisms), components=rows,
                instancesPlaced=sum(r['placed'] for r in rows),
                instancesPlanned=sum(r['planned'] for r in rows)), deck_cells


def measure(native, offline, deck_cells):
    """THE ACCEPTANCE. Coverage of the sourced polygon, and the clearance between the PLACED
    deck and the cut terrain under it - both computed from what is in the level, not from the
    plan file and not from the terrain cut's own receipt."""
    polygon = plaza_polygon()
    polygon_area_cm2 = abs(gen.polygon_area(polygon))
    thickness = float(offline['deckThicknessCm'])

    # Cells and undersides FROM THE PLACED INSTANCES.
    regions = []
    deck_area_cm2 = 0.0
    for x, y, z, sx, sy, sz in deck_cells:
        if abs(sz - 1.0) > 1e-6:
            raise RuntimeError('A placed deck cell is scaled in Z by %g' % sz)
        half_x, half_y = 625.0 * sx, 625.0 * sy
        regions.append(([x - half_x, y - half_y, x + half_x, y + half_y], z - thickness))
        deck_area_cm2 += (2 * half_x) * (2 * half_y)
    index = cut.RegionIndex(regions)
    bbox = [min(r[0][0] for r in regions), min(r[0][1] for r in regions),
            max(r[0][2] for r in regions), max(r[0][3] for r in regions)]

    # The terrain. The plaza is a MODERN feature, so the surface it must clear is the one
    # MODERN shows: the KotelPlazaCut twin. The YECHEZKEL-state surface is measured too, and
    # reported, because it is buried 11 m under the precinct deck and is expected to fail.
    terrain_rows = native.terrain_over_plaza(bbox)
    fields = {}
    for row in terrain_rows:
        mesh = native.ue.load_asset(row['meshPath'])
        if mesh is None:
            continue
        field = cut.HeightField()
        field.add(native.extract(mesh))
        fields[row['label']] = (row, field)
    twin_row = next((v for v in fields.values()
                     if v[0]['meshPath'] == TERRAIN_TWIN), None)
    if twin_row is None:
        raise RuntimeError('The KotelPlazaCut twin (%s) is not in the level over the plaza; '
                           'terrain actors found: %s'
                           % (TERRAIN_TWIN, [r['label'] for r in terrain_rows]))

    stations, nx, ny, dx, dy = cut.grid_stations(bbox, SAMPLE_SPACING_CM)
    in_polygon = on_deck = off_polygon_deck = 0
    per_surface = {}
    for label, (row, field) in fields.items():
        per_surface[label] = dict(
            mesh=row['mesh'], meshPath=row['meshPath'],
            hiddenInGameOnDisk=row['hiddenInGame'], tags=row['tags'],
            stations=0, missing=0, clearances=[])
    for x, y in stations:
        inside = gen.point_in_polygon((x, y), polygon)
        if inside:
            in_polygon += 1
        target = index.target(x, y)
        if target is None:
            continue
        on_deck += 1
        if not inside:
            off_polygon_deck += 1
        for label, (row, field) in fields.items():
            z = field.height(x, y)
            bucket = per_surface[label]
            if z is None:
                bucket['missing'] += 1
                continue
            bucket['stations'] += 1
            bucket['clearances'].append(target - z)

    def summarise(values):
        if not values:
            return None
        ordered = sorted(values)
        n = len(ordered)
        return dict(
            stations=n,
            minCm=round(ordered[0], 9),
            p05Cm=round(ordered[max(0, int(round(0.05 * (n - 1))))], 4),
            medianCm=round(ordered[(n - 1) // 2], 4),
            p95Cm=round(ordered[min(n - 1, int(round(0.95 * (n - 1))))], 4),
            maxCm=round(ordered[-1], 4),
            stationsWithTerrainAboveDeckUnderside=sum(1 for v in ordered if v < -TOLERANCE_CM),
            maxTerrainHeightAboveDeckUndersideCm=round(-ordered[0], 9))

    surfaces = {}
    for label, bucket in per_surface.items():
        surfaces[label] = dict(
            mesh=bucket['mesh'], meshPath=bucket['meshPath'],
            hiddenInGameOnDisk=bucket['hiddenInGameOnDisk'], tags=bucket['tags'],
            isTheModernSurface=(bucket['meshPath'] == TERRAIN_TWIN),
            stationsWithNoTerrain=bucket['missing'],
            clearance=summarise(bucket['clearances']))

    twin_label = twin_row[0]['label']
    headline = surfaces[twin_label]['clearance']
    return dict(
        method=('A %g cm grid over the placed deck bbox. A station counts as ON DECK when it '
                'falls inside a placed deck cell; clearance is that cell\'s underside minus '
                'the terrain height under it, so POSITIVE is deck above ground and NEGATIVE '
                'is terrain piercing the slab.' % SAMPLE_SPACING_CM),
        gridSpacingCm=SAMPLE_SPACING_CM, gridStationsX=nx, gridStationsY=ny,
        exactSpacingXCm=round(dx, 6), exactSpacingYCm=round(dy, 6),
        stationsSampled=len(stations),
        deckBboxCm=[round(v, 4) for v in bbox],
        coverage=dict(
            polygonOsmWay=offline['osmWay'],
            polygonVertices=len(polygon),
            polygonAreaM2=round(polygon_area_cm2 / 1e4, 3),
            deckAreaFromPlacedInstancesM2=round(deck_area_cm2 / 1e4, 3),
            deckAreaVersusPolygonPercent=round(100.0 * deck_area_cm2 / polygon_area_cm2, 3),
            stationsInsidePolygon=in_polygon,
            stationsOnDeck=on_deck,
            stationsOnDeckOutsidePolygon=off_polygon_deck,
            stationCoverageOfPolygonPercent=(round(100.0 * (on_deck - off_polygon_deck)
                                                   / in_polygon, 3) if in_polygon else None),
            note=('Two independent coverage numbers: the summed area of the 926 placed cells '
                  'against the sourced polygon, and the fraction of a %g cm grid of '
                  'in-polygon stations that lands on placed deck. They are computed by '
                  'different arithmetic and should agree.' % SAMPLE_SPACING_CM)),
        modernSurface=dict(
            actorLabel=twin_label, meshPath=TERRAIN_TWIN,
            why=('The plaza is a MODERN feature; the terrain MODERN shows under it is the '
                 'KotelPlazaCut twin. This is the clearance the acceptance is about.'),
            clearance=headline),
        allTerrainSurfacesOverThePlaza=surfaces,
        terrainActorsOverThePlaza=terrain_rows)


# =====================================================================================
# Run
# =====================================================================================
def run(target_key, mode, revert_receipt=None, rebuild=False):
    import unreal as ue
    if Path(ue.Paths.project_dir()).resolve() != ROOT:
        raise RuntimeError('Wrong project directory: ' + ue.Paths.project_dir())

    offline = offline_plan()
    if not offline['offlineOk']:
        raise RuntimeError('Offline plan has failures: %r' % offline['failures'])
    plan = json.loads(PLAN_PATH.read_text(encoding='utf-8-sig'))
    components = offline['components']

    stamp = stamp_now()
    native = Native(ue, target_key, mode, stamp)
    config = native.config
    target_map = config['map']
    map_file = ROOT / ('Content' + target_map[len('/Game'):] + '.umap')
    if not map_file.is_file():
        raise RuntimeError('Target map file missing: ' + str(map_file))

    if native.editor.get_game_world():
        raise RuntimeError('A game world is active; never mutate during play')
    if ue.EditorLoadingAndSavingUtils.get_dirty_map_packages() or \
       ue.EditorLoadingAndSavingUtils.get_dirty_content_packages():
        raise RuntimeError('Dirty packages present; resolve before checkpointed work')

    map_sha_before = sha256_of(map_file)
    protected_maps = {m: sha256_of(disk_path(m, 'umap')) for m in cut.PROTECTED_MAPS
                      if m != target_map and disk_path(m, 'umap').exists()}
    protected_assets = {TERRAIN_TWIN: sha256_of(disk_path(TERRAIN_TWIN))}
    for spec in components:
        protected_assets[spec['mesh']] = sha256_of(disk_path(spec['mesh']))
        protected_assets[spec['material']] = sha256_of(disk_path(spec['material']))
    protected_assets[KOTEL_MESH] = (sha256_of(disk_path(KOTEL_MESH))
                                    if disk_path(KOTEL_MESH).is_file() else None)

    native.receipt_path = FOLDER / ('native-kotel-plaza-%s-%s-%s.json'
                                    % (mode, config['key'], stamp))
    if native.receipt_path.exists():
        raise RuntimeError('Receipt already exists: ' + str(native.receipt_path))

    checkpoint = None
    if mode in ('apply', 'revert'):
        checkpoint = CHECKPOINT_ROOT / ('KotelPlaza-%s-%s' % (config['key'], stamp))
        checkpoint.mkdir(parents=True, exist_ok=False)
        shutil.copy2(map_file, checkpoint / map_file.name)
        if sha256_of(checkpoint / map_file.name) != map_sha_before:
            raise RuntimeError('Checkpoint copy hash differs from the live map')
        for folder_name in ('__ExternalActors__', '__ExternalObjects__'):
            external = ROOT / 'Content' / folder_name / target_map[6:]
            if external.exists():
                shutil.copytree(external, checkpoint / folder_name / target_map[6:])

    scale, translation = map_targets.placement_of(target_key)
    native.receipt = {
        'status': 'started_' + mode,
        'script': SCRIPT_TOKEN,
        'mode': mode, 'target': config['key'], 'stamp': stamp,
        'map': target_map, 'mapFile': str(map_file), 'mapSha256Before': map_sha_before,
        'checkpoint': str(checkpoint) if checkpoint else None,
        'protectedMapSha256Before': protected_maps,
        'protectedAssetSha256Before': protected_assets,
        'scriptSha256': offline['scriptSha256'],
        'engineVersion': ue.SystemLibrary.get_engine_version(),
        'userInstruction': ('"i also want you to restore the old city to its current modern '
                            'day layout... with kotel plaza and then houses up to that point" '
                            '- 9 September 2026. The houses half needed nothing; this is the '
                            'plaza half.'),
        'plan': offline,
        'placement': {
            'appliedTransform': 'identity',
            'declaredArchitecturePlacementForThisTarget': {
                'uniformScale': scale, 'translationCm': translation,
                'derivation': config['derivation']},
            'why': ('The plaza stands on the GROUND, not on the architecture. The 0.96 / '
                    '(-248, 0, 0) similarity was applied to the 2,633 architecture actors '
                    'only; the metric city and the 256 DEM ground tiles were never rescaled. '
                    'The decisive evidence is the terrain cut itself: kotel_job() in '
                    'release_precinct_terrain_cut.py takes no target argument, both maps cut '
                    'the same tile over the same 146 rectangles, and both read back the same '
                    '5,533 stations and the same 5.859375278305379e-06 cm. A plaza placed at '
                    '0.96 scale would not sit on the hole that was cut for it. Recorded as a '
                    'MEASUREMENT below in groundFrame and architectureFrame, not as a claim.'),
            'groundFrame': None, 'groundProof': None, 'architectureFrame': None},
        'stateContract': {
            'actorTags': [IDENTITY_TAG, STATE_TAG],
            'stateTag': STATE_TAG,
            'behaviour': ('%s is already in AMikdashEnclosure::HideWhileWallStandsTags '
                          '(MikdashEnclosure.cpp:204), so the actor is hidden while the '
                          'Yechezkel precinct stands and shown in MODERN and OVERLAY. No '
                          'plugin change and no rebuild is needed.' % STATE_TAG),
            'sharedWithTheTerrainTwin': ('Deliberate. The deck and the cut ground it stands '
                                         'in must appear and disappear together; one tag '
                                         'makes it impossible for them to disagree.'),
            'onDisk': 'hidden, collision off - the YECHEZKEL-correct state, as the twin was left.',
            'cannotBeCaughtByTheBuildingHidePath': (
                'BuildingIdentityLabel returns an empty label for a HISM-only actor and '
                'GatherModernBuildings skips empty labels, so no value in ExplicitHideLabels, '
                'ExplicitHideMeshNames or ModernBuildingLabelPrefixes can reach this actor.')},
        'reading': offline['reading'],
        'notBuilt': offline['notBuilt'],
        'limitations': offline['limitations'],
        'placed': [], 'readback': None, 'acceptance': None,
        'errors': [], 'mapSaved': False,
    }
    native.write_receipt()

    saved = False
    try:
        if not native.levels.load_level(target_map):
            raise RuntimeError('load_level failed for ' + target_map)
        world = native.editor.get_editor_world()
        if world.get_outermost().get_name() != target_map:
            raise RuntimeError('Loaded world is not the target map')

        rows = native.snapshot_rows()
        native.receipt['levelActorsWithAStaticMesh'] = len(rows)
        native.receipt['placement']['groundFrame'] = native.ground_frame(rows)
        native.receipt['placement']['groundProof'] = native.prove_ground(rows)
        by_key, _manifest = map_targets.architecture_index()
        native.receipt['placement']['architectureFrame'] = map_targets.prove_placement(
            rows, by_key, scale, translation)
        native.write_receipt()

        existing = native.plaza_actors()
        native.receipt['existingPlazaActorsBefore'] = [
            dict(name=a.get_name(), label=a.get_actor_label()) for a in existing]

        if mode == 'apply':
            if existing and not rebuild:
                raise RuntimeError('%d plaza actor(s) already in this map; pass -PlazaRebuild '
                                   'to replace, or -PlazaVerify to measure what is there'
                                   % len(existing))
            for actor in existing:
                native.actors.destroy_actor(actor)
            native.receipt['rebuiltOver'] = len(existing)
            _actor, placed = native.build(plan, components)
            native.receipt['placed'] = placed
            native.write_receipt()
            if not native.levels.save_current_level():
                raise RuntimeError('save_current_level returned False')
            saved = True
            native.receipt['mapSaved'] = True
            native.receipt['mapSha256AfterSave'] = sha256_of(map_file)
            native.write_receipt()
            if not native.levels.load_level(target_map):
                raise RuntimeError('Reopen failed')

        if mode == 'revert':
            prior = json.loads(Path(revert_receipt).read_text(encoding='utf-8-sig'))
            if prior.get('target') != config['key'] or prior.get('mode') != 'apply' \
                    or not prior.get('mapSaved'):
                raise RuntimeError('Revert needs a SAVED apply receipt for this target')
            label = prior['readback']['actorLabel'] if prior.get('readback') else ACTOR_LABEL
            destroyed = []
            for actor in native.plaza_actors():
                if actor.get_actor_label() == label:
                    destroyed.append(dict(name=actor.get_name(), label=label))
                    native.actors.destroy_actor(actor)
            if not destroyed:
                raise RuntimeError('Nothing to revert: no actor labelled ' + label)
            native.receipt['reverted'] = destroyed
            if not native.levels.save_current_level():
                raise RuntimeError('save_current_level returned False')
            saved = True
            native.receipt['mapSaved'] = True
            native.receipt['mapSha256AfterSave'] = sha256_of(map_file)
            if not native.levels.load_level(target_map):
                raise RuntimeError('Reopen failed')
            remaining = native.plaza_actors()
            native.receipt['plazaActorsAfterRevert'] = [a.get_actor_label() for a in remaining]
            if remaining:
                raise RuntimeError('Plaza actors survive the revert: %s'
                                   % native.receipt['plazaActorsAfterRevert'])
            native.receipt['status'] = 'kotel_plaza_reverted_saved_reopened'

        if mode in ('apply', 'verify'):
            readback, deck_cells = read_back(native, plan, components)
            native.receipt['readback'] = readback
            native.write_receipt()
            native.receipt['acceptance'] = measure(native, offline, deck_cells)
            headline = native.receipt['acceptance']['modernSurface']['clearance']
            if headline['stationsWithTerrainAboveDeckUnderside'] > 0:
                raise RuntimeError(
                    'The cut terrain still pierces the placed deck at %d of %d stations, worst '
                    '%.4f cm above the underside'
                    % (headline['stationsWithTerrainAboveDeckUnderside'], headline['stations'],
                       headline['maxTerrainHeightAboveDeckUndersideCm']))
            native.receipt['status'] = (
                'kotel_plaza_placed_saved_reopened_measured_visual_acceptance_pending'
                if mode == 'apply' else 'kotel_plaza_measured_map_unchanged')
    except Exception as error:                                               # noqa: BLE001
        native.receipt['errors'].append({'stage': mode, 'error': repr(error)})
        native.receipt['status'] = ('FAILED_AFTER_SAVE_CHECKPOINT_AVAILABLE' if saved
                                    else 'FAILED_BEFORE_SAVE_MAP_UNCHANGED')
        raise
    finally:
        native.receipt['mapSha256After'] = sha256_of(map_file)
        native.receipt['mapBytesChanged'] = \
            native.receipt['mapSha256After'] != map_sha_before
        native.receipt['protectedMapsUnchanged'] = all(
            sha256_of(disk_path(m, 'umap')) == value for m, value in protected_maps.items())
        native.receipt['protectedAssetsUnchanged'] = all(
            value is None or sha256_of(disk_path(p)) == value
            for p, value in protected_assets.items())
        if mode == 'verify' and native.receipt['mapBytesChanged']:
            native.receipt['errors'].append(
                {'stage': 'finally', 'error': '-PlazaVerify must not change the map, and it did.'})
        native.write_receipt()
    return native.receipt


# =====================================================================================
# Entry
# =====================================================================================
def _flag(command_line, table, what):
    tokens = [t.strip('"').lower() for t in command_line.split()]
    found = sorted({value for token in tokens for key, value in table.items()
                    if token == key or token.startswith(key + '=')})
    if len(found) > 1:
        raise RuntimeError('More than one %s flag: %s' % (what, found))
    return found[0] if found else None


def _main():
    try:
        import unreal                                                        # noqa: F401
        native = True
    except ImportError:
        native = False

    if not native:
        action = map_targets.revert_from_command_line()
        if action:
            print(json.dumps(map_targets.restore_checkpoint(action['receipt'],
                                                            dry_run=action['dryRun']), indent=2))
            return
        planned = offline_plan()
        print(json.dumps(planned, indent=2, default=str))
        if not planned['offlineOk']:
            raise SystemExit('Offline plan has failures: %r' % planned['failures'])
        return

    import unreal as ue
    command_line = ue.SystemLibrary.get_command_line()
    mode = _flag(command_line, MODE_FLAGS, 'mode')
    if not mode:
        raise RuntimeError('Choose exactly one mode: %s' % sorted(set(MODE_FLAGS.values())))
    target_key = map_targets.target_from_command_line(command_line=command_line)
    revert_receipt = None
    if mode == 'revert':
        import re
        match = re.search(r'-PlazaRevert=(?:"([^"]+)"|(\S+))', command_line, re.IGNORECASE)
        if not match:
            raise RuntimeError('-PlazaRevert needs =<apply receipt path>')
        revert_receipt = match.group(1) or match.group(2)
    rebuild = '-plazarebuild' in command_line.lower()
    try:
        receipt = run(target_key, mode, revert_receipt, rebuild)
        acceptance = receipt.get('acceptance') or {}
        clearance = ((acceptance.get('modernSurface') or {}).get('clearance') or {})
        ue.log('release_kotel_plaza[%s/%s]: %s; instances %s/%s; coverage %s%%; '
               'min clearance %s cm; errors %d'
               % (receipt['target'], mode, receipt['status'],
                  (receipt.get('readback') or {}).get('instancesPlaced'),
                  (receipt.get('readback') or {}).get('instancesPlanned'),
                  (acceptance.get('coverage') or {}).get('stationCoverageOfPolygonPercent'),
                  clearance.get('minCm'), len(receipt['errors'])))
    except Exception as error:                                               # noqa: BLE001
        ue.log_error('release_kotel_plaza failed: ' + repr(error))
        raise


if __name__ == '__main__':
    _main()
