# GENERATED by generate.py; isolated 30-float candidate, no import-time Unreal work.

def _set(obj, name, value, cmp=None):
    obj.set_editor_property(name, value)
    got = obj.get_editor_property(name)
    ok = cmp(got, value) if cmp else got == value
    if not ok:
        raise RuntimeError('Readback mismatch on %s.%s: wrote %r read %r' % (type(obj).__name__, name, value, got))
    return got

def _path(obj):
    return obj.get_path_name() if obj else None

class Graph:
    def __init__(self, ue, material, receipt):
        self.ue, self.m, self.ml = ue, material, ue.MaterialEditingLibrary
        self.pins = receipt.setdefault('resolvedPins', [])

    def make(self, cls, x=0, y=0, **props):
        node = self.ml.create_material_expression(self.m, cls, x, y)
        if not node:
            raise RuntimeError('create_material_expression failed for ' + cls.__name__)
        for key, value in props.items():
            node.set_editor_property(key, value)
        return node

    def wire(self, src, dst, wanted, out=''):
        live = [str(n) for n in self.ml.get_material_expression_input_names(dst)]
        target = None
        for name in live:
            if name.lower() == wanted.lower():
                target = name
        if target is None and len(live) == 1:
            target = live[0]
        if target is None:
            raise RuntimeError('%s has no input %r (live %r)' % (dst.get_class().get_name(), wanted, live))
        if not self.ml.connect_material_expressions(src, out, dst, target):
            raise RuntimeError('connect %s -> %s.%s failed' % (src.get_class().get_name(), dst.get_class().get_name(), target))
        self.pins.append([dst.get_class().get_name(), wanted, target])

    def prop(self, src, prop):
        if not self.ml.connect_material_property(src, '', prop):
            raise RuntimeError('connect_material_property failed for %s' % prop)

    def custom(self, code, inputs, x, y, desc):
        ue = self.ue
        node = self.make(ue.MaterialExpressionCustom, x, y)
        node.set_editor_property('code', code)
        node.set_editor_property('output_type', ue.CustomMaterialOutputType.CMOT_FLOAT3)
        node.set_editor_property('description', desc)
        pins = []
        for name in inputs:
            pin = ue.CustomInput()
            pin.set_editor_property('input_name', name)
            pins.append(pin)
        node.set_editor_property('inputs', pins)
        got = [str(p.get_editor_property('input_name')) for p in node.get_editor_property('inputs')]
        if got != list(inputs):
            raise RuntimeError('Custom inputs did not take: %r' % got)
        return node

    def scalar(self, name, value, x, y):
        return self.make(self.ue.MaterialExpressionScalarParameter, x, y, parameter_name=name, default_value=float(value))

    def vector(self, name, rgb, x, y):
        node = self.make(self.ue.MaterialExpressionVectorParameter, x, y, parameter_name=name)
        node.set_editor_property('default_value', self.ue.LinearColor(float(rgb[0]), float(rgb[1]), float(rgb[2]), 1.0))
        return node

    def custom_data(self, index, default, x, y):
        node = self.make(self.ue.MaterialExpressionPerInstanceCustomData, x, y)
        _set(node, 'data_index', int(index))
        _set(node, 'const_default_value', float(default), lambda a, b: abs(a - b) < 1e-6)
        return node

    def texture_param(self, name, texture, x, y):
        ue = self.ue
        node = self.make(ue.MaterialExpressionTextureObjectParameter, x, y, parameter_name=name)
        node.set_editor_property('texture', texture)
        node.set_editor_property('sampler_type', ue.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR)
        return node

class StockGraph(Graph):
    def pin(self, dst, candidates):
        live = [str(n) for n in self.ml.get_material_expression_input_names(dst)]
        for c in candidates:
            for name in live:
                if name.lower() == str(c).lower():
                    return name
        if len(live) == 1:
            return live[0]
        raise RuntimeError('%s has none of %r (live %r)' % (dst.get_class().get_name(), candidates, live))

    def link(self, src, dst, candidates):
        node, out = src if isinstance(src, tuple) else (src, '')
        name = self.pin(dst, candidates)
        if not self.ml.connect_material_expressions(node, out, dst, name):
            raise RuntimeError('connect %s.%r -> %s.%s failed' % (node.get_class().get_name(), out, dst.get_class().get_name(), name))
        self.pins.append([dst.get_class().get_name(), name, out])

    def const(self, value):
        node = self.make(self.ue.MaterialExpressionConstant)
        _set(node, 'r', float(value), lambda a, b: abs(a - b) < 1e-6)
        return node

    def const3(self, rgb):
        node = self.make(self.ue.MaterialExpressionConstant3Vector)
        node.set_editor_property('constant', self.ue.LinearColor(float(rgb[0]), float(rgb[1]), float(rgb[2]), 1.0))
        got = node.get_editor_property('constant')
        if any(abs(float(x) - float(y)) > 1e-4 for x, y in zip((got.r, got.g, got.b), rgb)):
            raise RuntimeError('Constant3Vector did not take %r' % (rgb,))
        return node

    def op(self, cls, a, b):
        node = self.make(cls)
        self.link(a, node, ['A'])
        self.link(b, node, ['B'])
        return node

    def unary(self, cls, a):
        node = self.make(cls)
        self.link(a, node, ['Input', 'None', '', 'VectorInput', 'X'])
        return node

    def lerp(self, a, b, alpha):
        node = self.make(self.ue.MaterialExpressionLinearInterpolate)
        self.link(a, node, ['A'])
        self.link(b, node, ['B'])
        self.link(alpha, node, ['Alpha'])
        return node

    def clamp(self, x, lo, hi):
        node = self.make(self.ue.MaterialExpressionClamp)
        self.link(x, node, ['Input', 'None', ''])
        self.link(lo, node, ['Min'])
        self.link(hi, node, ['Max'])
        return node

    def mask(self, x, channels):
        # 5.8 trap: a new ComponentMask starts with R, G and B ticked. Set all four, read back.
        node = self.make(self.ue.MaterialExpressionComponentMask)
        for ch in 'rgba':
            _set(node, ch, ch in channels)
        self.link(x, node, ['Input', 'None', ''])
        return node

    def tex(self, name, texture, uv):
        ue = self.ue
        node = self.make(ue.MaterialExpressionTextureSampleParameter2D)
        _set(node, 'parameter_name', name, lambda a, b: str(a) == str(b))
        node.set_editor_property('texture', texture)
        _set(node, 'sampler_type', ue.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR)
        # Vertex-stage sampling needs an explicit mip: MipLevel mode, level 0 (the VAT has no mips).
        _set(node, 'mip_value_mode', ue.TextureMipValueMode.TMVM_MIP_LEVEL)
        _set(node, 'const_mip_value', 0)
        self.link(uv, node, ['UVs', 'Coordinates'])
        outs = [str(n) for n in self.ml.get_material_expression_output_names(node)] \
            if hasattr(self.ml, 'get_material_expression_output_names') else ['RGB']
        if 'RGB' not in outs:
            raise RuntimeError('TextureSampleParameter2D has no RGB output: %r' % outs)
        return (node, 'RGB')

def _transform(g, src):
    ue = g.ue
    node = g.make(ue.MaterialExpressionTransform)
    _set(node, 'transform_source_type', ue.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_LOCAL)
    _set(node, 'transform_type', ue.MaterialVectorCoordTransform.TRANSFORM_WORLD)
    g.link(src, node, ['Input', 'None', ''])
    return node

def stock_angle(g, time, start, delta):
    """g is the existing StockGraph; all operations are stock vertex expressions."""
    e = g.ue
    elapsed = g.op(e.MaterialExpressionMax, g.op(e.MaterialExpressionSubtract, time, start), g.const(0.0))
    travel = g.op(e.MaterialExpressionMin, g.op(e.MaterialExpressionMultiply, elapsed, g.const(90.0)),
                  g.unary(e.MaterialExpressionAbs, delta))
    return g.op(e.MaterialExpressionMultiply, g.unary(e.MaterialExpressionSign, delta), travel)

def stock_rotate(g, value, degrees):
    e = g.ue
    c, s = g.make(e.MaterialExpressionCosine), g.make(e.MaterialExpressionSine)
    for node in (c, s):
        node.set_editor_property('period', 360.0)
        g.link(degrees, node, ['Input'])
    x, y, z = (g.mask(value, component) for component in 'rgb')
    mul, add, sub, append = e.MaterialExpressionMultiply, e.MaterialExpressionAdd, e.MaterialExpressionSubtract, e.MaterialExpressionAppendVector
    return g.op(append, g.op(append, g.op(sub, g.op(mul,c,x),g.op(mul,s,y)),
                            g.op(add,g.op(mul,s,x),g.op(mul,c,y))),z)

def stock_posed_delta(g, rest, vat_delta, degrees):
    e = g.ue
    return g.op(e.MaterialExpressionSubtract,
                stock_rotate(g, g.op(e.MaterialExpressionAdd, rest, vat_delta), degrees), rest)

# Stock-node implementation of CurvePacket.ush, embedded by generate.py.
def curve_if(g,a,b,greater,equal,less):
 n=g.make(g.ue.MaterialExpressionIf);n.set_editor_property('equals_threshold',0.0)
 for value,pin in [(a,'A'),(b,'B'),(greater,'A > B'),(equal,'A == B'),(less,'A < B')]:g.link(value,n,[pin])
 return n

def curve_choose(g,enabled,yes,no):return curve_if(g,enabled,g.const(1),no,yes,no)

def curve_eval(g,time,base):
 cache=getattr(g,'curve_cache',None)
 if cache is None:cache={};g.curve_cache=cache
 key=(id(time),base)
 if key in cache:return cache[key]
 e=g.ue;add=e.MaterialExpressionAdd;sub=e.MaterialExpressionSubtract;mul=e.MaterialExpressionMultiply;div=e.MaterialExpressionDivide
 A=lambda x,y:g.op(add,x,y);S=lambda x,y:g.op(sub,x,y);M=lambda x,y:g.op(mul,x,y);D=lambda x,y:g.op(div,x,y)
 V=lambda x,y,z:g.op(e.MaterialExpressionAppendVector,g.op(e.MaterialExpressionAppendVector,x,y),z)
 p=[g.custom_data(base+i,0,0,0) for i in range(23)];zero=g.const(0);one=g.const(1)
 R=g.op(e.MaterialExpressionMax,p[8],g.const(.001));duration=g.op(e.MaterialExpressionMax,p[13],g.const(.001))
 d=D(M(g.clamp(S(time,p[12]),zero,duration),p[11]),duration)
 arc=g.clamp(S(d,p[9]),zero,p[10]);theta=D(arc,R)
 def trig(kind,x):
  n=g.make(kind);n.set_editor_property('period',6.283185307179586);g.link(x,n,['Input']);return n
 along=A(g.op(e.MaterialExpressionMin,d,p[9]),M(R,trig(e.MaterialExpressionSine,theta)))
 across=A(M(R,S(one,trig(e.MaterialExpressionCosine,theta))),g.op(e.MaterialExpressionMax,S(S(d,p[9]),p[10]),zero))
 origin=V(p[1],p[2],p[3]);u=V(p[4],p[5],zero);v=V(p[6],p[7],zero);tail=V(p[17],p[18],p[19])
 root=A(A(origin,M(u,along)),M(v,across));endtheta=D(p[10],R)
 end=A(A(origin,M(u,A(p[9],M(R,trig(e.MaterialExpressionSine,endtheta))))),M(v,A(M(R,S(one,trig(e.MaterialExpressionCosine,endtheta))),g.op(e.MaterialExpressionMax,S(S(p[11],p[9]),p[10]),zero))))
 alpha=M(g.unary(e.MaterialExpressionSaturate,D(S(S(time,p[12]),duration),g.op(e.MaterialExpressionMax,p[20],g.const(.001)))),p[16])
 delta=S(tail,end);sq=M(delta,delta);norm=g.unary(e.MaterialExpressionSquareRoot,A(A(g.mask(sq,'r'),g.mask(sq,'g')),g.mask(sq,'b')))
 distance=A(d,M(norm,alpha));active=curve_if(g,p[0],one,curve_if(g,p[0],g.const(2),zero,one,zero),one,zero);enabled=curve_if(g,g.custom_data(30,0,0,0),g.const(9001),zero,active,zero)
 out={'root':g.lerp(root,tail,alpha),'yaw':A(p[14],M(M(p[15],theta),g.const(57.29577951308232))),'phase':g.unary(e.MaterialExpressionFrac,A(p[21],M(distance,p[22]))),'enabled':enabled}
 cache[key]=out;return out

def curve_wpo(g,time,base,rest,delta,to_world,legacy):
 q=curve_eval(g,time,base);posed=stock_posed_delta(g,rest,delta,q['yaw'])
 return curve_choose(g,q['enabled'],g.op(g.ue.MaterialExpressionAdd,q['root'],to_world(posed)),legacy)

def curve_previous_normal(g,time,current,clip,frames,uvw,defaults,idle_normal,idle_weight,blend,negdt,to_world):
 e=g.ue;add=e.MaterialExpressionAdd;sub=e.MaterialExpressionSubtract;mul=e.MaterialExpressionMultiply;div=e.MaterialExpressionDivide
 cd=lambda i:g.custom_data(i,1 if i==14 else 0,0,0)
 dt=g.clamp(g.op(sub,time,cd(17)),g.op(mul,negdt,g.const(-1)),cd(24))
 legacyphase=g.unary(e.MaterialExpressionFrac,g.op(add,cd(16),g.op(mul,dt,cd(18))))
 q=curve_eval(g,time,54);phase=curve_choose(g,q['enabled'],q['phase'],legacyphase)
 w=g.unary(e.MaterialExpressionSaturate,g.op(div,g.op(sub,time,cd(23)),blend))
 weight=g.lerp(g.unary(e.MaterialExpressionOneMinus,w),w,cd(22))
 walk=g.op(sub,g.op(mul,clip(phase,frames,uvw,'WalkNormalTexture',defaults['WalkNormalTexture']),g.const(2)),g.const(1))
 n=g.unary(e.MaterialExpressionNormalize,g.op(add,g.lerp(walk,idle_normal,weight),g.const3([0,0,1e-4])))
 old=stock_rotate(g,n,stock_angle(g,time,cd(28),cd(29)));x,y,z=[g.mask(old,c) for c in 'rgb']
 V=lambda a,b,c:g.op(e.MaterialExpressionAppendVector,g.op(e.MaterialExpressionAppendVector,a,b),c)
 old=V(g.op(sub,g.op(mul,cd(14),x),g.op(mul,cd(15),y)),g.op(add,g.op(mul,cd(15),x),g.op(mul,cd(14),y)),z)
 old=curve_choose(g,q['enabled'],stock_rotate(g,n,q['yaw']),old)
 old=g.unary(e.MaterialExpressionNormalize,to_world(old))
 selected=curve_if(g,time,cd(25),current,current,old)
 switch=g.make(e.MaterialExpressionPreviousFrameSwitch);g.link(current,switch,['Current Frame']);g.link(selected,switch,['Previous Frame']);return switch


def previous_wpo(g, time, cd, current_wpo, clip, walk_frames, uvw,
                 defaults, walk_size, walk_min, idle_position, blend, negdt, to_world):
    e = g.ue
    add, sub, mul, div = (e.MaterialExpressionAdd, e.MaterialExpressionSubtract,
                          e.MaterialExpressionMultiply, e.MaterialExpressionDivide)
    data = {i: g.custom_data(i, 1.0 if i == 14 else -1000.0 if i == 23 else 0.0, 0, 0)
            for i in range(11, 26)}
    vector = lambda x, y, z: g.op(e.MaterialExpressionAppendVector,
                                 g.op(e.MaterialExpressionAppendVector, x, y), z)
    old_dt = g.clamp(g.op(sub, time, data[17]), g.op(mul, negdt, g.const(-1)), data[24])
    old_phase = g.unary(e.MaterialExpressionFrac, g.op(add, data[16], g.op(mul, old_dt, data[18])))
    q=curve_eval(g,time,54);old_phase=curve_choose(g,q['enabled'],q['phase'],old_phase)
    old_walk = g.op(add, g.op(mul, clip(old_phase, walk_frames, uvw,
                       'WalkPositionTexture', defaults['WalkPositionTexture']), walk_size), walk_min)
    weight = g.unary(e.MaterialExpressionSaturate, g.op(div, g.op(sub, time, data[23]), blend))
    idle_weight = g.lerp(g.unary(e.MaterialExpressionOneMinus, weight), weight, data[22])
    old_delta = g.lerp(old_walk, idle_position, idle_weight)
    rest = g.make(e.MaterialExpressionPreSkinnedPosition)
    old_angle = stock_angle(g, time, g.custom_data(28, 0, 0, 0), g.custom_data(29, 0, 0, 0))
    old_local = stock_rotate(g, g.op(add, rest, old_delta), old_angle)
    x, y, z = (g.mask(old_local, c) for c in 'rgb')
    rotated = vector(g.op(sub, g.op(mul, data[14], x), g.op(mul, data[15], y)),
                     g.op(add, g.op(mul, data[15], x), g.op(mul, data[14], y)), z)
    # Rest is already positioned with the CURRENT instance matrix by the vertex
    # factory. Replace its orientation as part of WPO, preserving constant scale.
    correction = to_world(g.op(sub, rotated, rest))
    offset = vector(data[11], data[12], data[13])
    drift = g.op(mul, vector(data[19], data[20], data[21]), old_dt)
    history_wpo = g.op(add, g.op(add, offset, correction), drift)
    history_wpo=curve_wpo(g,time,54,rest,old_delta,to_world,history_wpo)
    select = g.make(e.MaterialExpressionIf)
    select.set_editor_property('equals_threshold', 0.0)
    g.link(time, select, ['A'])
    g.link(data[25], select, ['B'])
    g.link(current_wpo, select, ['A > B', 'AGreaterThanB'])
    g.link(current_wpo, select, ['A == B', 'AEqualsB'])
    g.link(history_wpo, select, ['A < B', 'ALessThanB'])
    switch = g.make(e.MaterialExpressionPreviousFrameSwitch)
    g.link(current_wpo, switch, ['Current Frame', 'CurrentFrame'])
    g.link(select, switch, ['Previous Frame', 'PreviousFrame'])
    return switch

def _build(ue, spec, ns, name, defaults, receipt):
    tools = ue.AssetToolsHelpers.get_asset_tools()
    assets = ue.EditorAssetLibrary
    folder = ns + '/Materials'
    if assets.does_asset_exist(folder + '/' + name):
        raise RuntimeError('%s already exists (build to a new name)' % name)
    material = tools.create_asset(name, folder, ue.Material, ue.MaterialFactoryNew())
    g = StockGraph(ue, material, receipt)
    E = ue
    mp = ue.MaterialProperty
    t = g.make(E.MaterialExpressionTime)
    cd_defaults = {0: 0.0, 1: 0.5, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: -1000.0, 9: 0.5, 10: 0.0}
    cd = {i: g.custom_data(i, d, 0, 0) for i, d in cd_defaults.items()}
    uvw = g.make(E.MaterialExpressionTextureCoordinate, coordinate_index=int(spec['walk']['uvChannel']))
    uvi = g.make(E.MaterialExpressionTextureCoordinate, coordinate_index=int(spec['idle']['uvChannel']))
    walk_frames = g.scalar('WalkFrames', spec['walk']['loopFrames'], 0, 0)
    idle_frames = g.scalar('IdleFrames', spec['idle']['loopFrames'], 0, 0)
    idle_seconds = g.scalar('IdleSeconds', spec['idle']['loopFrames'] / spec['idle']['sampleRateHz'], 0, 0)
    blend = g.scalar('BlendSeconds', spec['material']['blendSeconds'], 0, 0)
    negdt = g.scalar('NegativeDtSeconds', spec['material']['negativeDtSeconds'], 0, 0)
    rgb = lambda node: g.mask(node, 'rgb')
    wmin = rgb(g.vector('WalkMinBBox', defaults['WalkMinBBox'], 0, 0))
    wsize = rgb(g.vector('WalkSizeBBox', defaults['WalkSizeBBox'], 0, 0))
    imin = rgb(g.vector('IdleMinBBox', defaults['IdleMinBBox'], 0, 0))
    isize = rgb(g.vector('IdleSizeBBox', defaults['IdleSizeBBox'], 0, 0))
    base = rgb(g.vector('BaseColor', [0.7, 0.65, 0.55], 0, 0))
    rough = g.scalar('Roughness', 0.85, 0, 0)
    spec_node = g.scalar('Specular', spec['material']['specular'], 0, 0)
    mix = g.scalar('PaletteMix', 0.0, 0, 0)
    skinvar = g.scalar('SkinVariation', 0.0, 0, 0)
    M, A, S, D = E.MaterialExpressionMultiply, E.MaterialExpressionAdd, E.MaterialExpressionSubtract, E.MaterialExpressionDivide

    # dt = clamp(t - T0, -NegDt, Horizon): the SAME clamp for travel and stride.
    dt = g.clamp(g.op(S, t, cd[3]), g.op(M, negdt, g.const(-1.0)), cd[10])
    walk_phase = g.unary(E.MaterialExpressionFrac, g.op(A, cd[0], g.op(M, dt, cd[4])))
    q=curve_eval(g,t,31);walk_phase=curve_choose(g,q['enabled'],q['phase'],walk_phase)
    idle_rate = g.op(A, g.const(0.92), g.op(M, g.const(0.16), g.unary(E.MaterialExpressionFrac, g.op(M, cd[9], g.const(7.31)))))
    idle_phase = g.unary(E.MaterialExpressionFrac, g.op(A, cd[9], g.op(D, g.op(M, t, idle_rate), idle_seconds)))
    w = g.unary(E.MaterialExpressionSaturate, g.op(D, g.op(S, t, cd[8]), blend))
    idle_w = g.lerp(g.unary(E.MaterialExpressionOneMinus, w), w, cd[2])

    def clip(phase, frames, uv, tex_name, tex_obj):
        fr = g.op(M, phase, frames)
        f0 = g.unary(E.MaterialExpressionFloor, fr)
        a = g.unary(E.MaterialExpressionFrac, fr)
        u = g.mask(uv, 'r')
        v = g.mask(uv, 'g')
        # AnimToTexture UV V contains the vertex row offset / texture height.
        # With R rows/frame and height=N*R, frame f adds f*R/(N*R)=f/N.
        # Frame N wraps to frame 0 through texture Wrap addressing.
        v0 = g.op(A, v, g.op(D, f0, frames))
        v1 = g.op(A, v, g.op(D, g.op(A, f0, g.const(1.0)), frames))
        s0 = g.tex(tex_name, tex_obj, g.op(E.MaterialExpressionAppendVector, u, v0))
        s1 = g.tex(tex_name, tex_obj, g.op(E.MaterialExpressionAppendVector, u, v1))
        return g.lerp(s0, s1, a)

    walk_p = g.op(A, g.op(M, clip(walk_phase, walk_frames, uvw, 'WalkPositionTexture', defaults['WalkPositionTexture']), wsize), wmin)
    idle_p = g.op(A, g.op(M, clip(idle_phase, idle_frames, uvi, 'IdlePositionTexture', defaults['IdlePositionTexture']), isize), imin)
    delta = g.lerp(walk_p, idle_p, idle_w)
    to_world = lambda src: _transform(g, src)
    drift = g.op(M, g.op(E.MaterialExpressionAppendVector, g.op(E.MaterialExpressionAppendVector, cd[5], cd[6]), cd[7]), dt)
    angle = stock_angle(g, t, g.custom_data(26, 0, 0, 0), g.custom_data(27, 0, 0, 0))
    rest = g.make(E.MaterialExpressionPreSkinnedPosition)
    wpo = g.op(A, to_world(stock_posed_delta(g, rest, delta, angle)), drift)
    wpo=curve_wpo(g,t,31,rest,delta,to_world,wpo)
    if True:
        wpo = previous_wpo(g, t, cd, wpo, clip, walk_frames, uvw,
                                   defaults, wsize, wmin, idle_p, blend, negdt, to_world)
    g.prop(wpo, mp.MP_WORLD_POSITION_OFFSET)

    decode = lambda x: g.op(S, g.op(M, x, g.const(2.0)), g.const(1.0))
    walk_n = decode(clip(walk_phase, walk_frames, uvw, 'WalkNormalTexture', defaults['WalkNormalTexture']))
    idle_n = decode(clip(idle_phase, idle_frames, uvi, 'IdleNormalTexture', defaults['IdleNormalTexture']))
    normal = g.unary(E.MaterialExpressionNormalize, g.op(A, g.lerp(walk_n, idle_n, idle_w), g.const3([0.0, 0.0, 1e-4])))
    n_interp = g.make(E.MaterialExpressionVertexInterpolator)
    angle=curve_choose(g,q['enabled'],q['yaw'],angle)
    current_normal=g.unary(E.MaterialExpressionNormalize,to_world(stock_rotate(g,normal,angle)))
    history_normal=curve_previous_normal(g,t,current_normal,clip,walk_frames,uvw,defaults,idle_n,idle_w,blend,negdt,to_world)
    g.link(history_normal,n_interp,['VS'])
    g.prop(n_interp, mp.MP_NORMAL)

    palette = spec['material']['palette']
    index = g.op(M, cd[1], g.const(len(palette) - 1))
    total = None
    for k, entry in enumerate(palette):
        weight = g.unary(E.MaterialExpressionSaturate, g.unary(E.MaterialExpressionOneMinus,
                         g.unary(E.MaterialExpressionAbs, g.op(S, index, g.const(k)))))
        term = g.op(M, weight, g.const3(entry))
        total = term if total is None else g.op(A, total, term)
    bright = g.op(A, g.const(0.90), g.op(M, g.const(0.20), g.unary(E.MaterialExpressionFrac, g.op(M, cd[9], g.const(13.7)))))
    garment = g.op(M, g.lerp(base, total, mix), bright)
    complexion = g.op(A, g.const(0.72), g.op(M, g.const(0.50), g.unary(E.MaterialExpressionFrac, g.op(M, cd[9], g.const(5.3)))))
    colour = g.lerp(garment, g.op(M, base, complexion), skinvar)
    c_interp = g.make(E.MaterialExpressionVertexInterpolator)
    g.link(colour, c_interp, ['VS'])
    g.prop(c_interp, mp.MP_BASE_COLOR)
    g.prop(rough, mp.MP_ROUGHNESS)
    g.prop(spec_node, mp.MP_SPECULAR)
    g.prop(g.const(0.0), mp.MP_METALLIC)

    _set(material, 'tangent_space_normal', False)
    _set(material, 'used_with_instanced_static_meshes', True)
    ml = ue.MaterialEditingLibrary
    census = {}
    for node in ml.get_material_expressions(material):
        census[node.get_class().get_name()] = census.get(node.get_class().get_name(), 0) + 1
    if census.get('MaterialExpressionCustom'):
        raise RuntimeError('A Custom node is in M_CrowdVAT_V2; the stock-node rule (EnclosureMath.h 6b) refuses it')
    # Caller validates before optional isolated save; no save/recompile here.
    receipt['masterV2'] = dict(path=_path(material), census=census, customNodes=census.get('MaterialExpressionCustom', 0),
                               usedWithInstancedStaticMeshes=bool(material.get_editor_property('used_with_instanced_static_meshes')),
                               tangentSpaceNormal=bool(material.get_editor_property('tangent_space_normal')))
    return material

def _surface(ue, master, report, surface_textures):
    """Use linear source colors and UV0 mottle with the existing VAT deformation."""
    ml = ue.MaterialEditingLibrary
    g = StockGraph(ue, master, report)
    mp = ue.MaterialProperty
    base = ml.get_material_property_input_node(master, mp.MP_BASE_COLOR)
    rough = ml.get_material_property_input_node(master, mp.MP_ROUGHNESS)
    assert base and rough
    vc = g.mask(g.make(ue.MaterialExpressionVertexColor), 'rgb')
    uv = g.make(ue.MaterialExpressionTextureCoordinate, coordinate_index=0)
    uv = g.op(ue.MaterialExpressionMultiply, uv, g.scalar('MottleTiling', .5, 0, 0))
    tex = g.make(ue.MaterialExpressionTextureSampleParameter2D)
    tex.set_editor_property('parameter_name', 'Mottle')
    tex.set_editor_property('texture', surface_textures['Mottle'])
    tex.set_editor_property('sampler_type', ue.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR)
    g.link(uv, tex, ['UVs'])
    centered = g.op(ue.MaterialExpressionSubtract, (tex,'R'), g.const(.5))
    mottle = g.op(ue.MaterialExpressionAdd, g.const(1.),
                  g.op(ue.MaterialExpressionMultiply, centered,
                       g.op(ue.MaterialExpressionMultiply, g.const(2.), g.scalar('MottleStrength', .3, 0, 0))))
    final = g.op(ue.MaterialExpressionMultiply, g.op(ue.MaterialExpressionMultiply, base, vc), mottle)
    g.prop(final, mp.MP_BASE_COLOR)
    g.prop(g.op(ue.MaterialExpressionAdd, rough, g.op(ue.MaterialExpressionMultiply, centered, g.const(.15))), mp.MP_ROUGHNESS)
    if True:
        # Reconstruct the tangent frame from the deformed position and UV0 in
        # the pixel shader; a rest-pose tangent would not follow VAT animation.
        M,A=ue.MaterialExpressionMultiply,ue.MaterialExpressionAdd
        cross=ue.MaterialExpressionCrossProduct
        dot=ue.MaterialExpressionDotProduct
        normal=g.unary(ue.MaterialExpressionNormalize,ml.get_material_property_input_node(master,mp.MP_NORMAL))
        position=g.make(ue.MaterialExpressionWorldPosition)
        uv0=g.make(ue.MaterialExpressionTextureCoordinate,coordinate_index=0)
        dp1=g.unary(ue.MaterialExpressionDDX,position)
        dp2=g.unary(ue.MaterialExpressionDDY,position)
        duv1=g.unary(ue.MaterialExpressionDDX,uv0)
        duv2=g.unary(ue.MaterialExpressionDDY,uv0)
        p2=g.op(cross,dp2,normal);p1=g.op(cross,normal,dp1)
        tangent=g.op(A,g.op(M,p2,g.mask(duv1,'r')),g.op(M,p1,g.mask(duv2,'r')))
        bitangent=g.op(A,g.op(M,p2,g.mask(duv1,'g')),g.op(M,p1,g.mask(duv2,'g')))
        length2=g.op(ue.MaterialExpressionMax,g.op(dot,tangent,tangent),g.op(dot,bitangent,bitangent))
        scale=g.op(ue.MaterialExpressionDivide,g.const(1.),g.unary(ue.MaterialExpressionSquareRoot,
                   g.op(ue.MaterialExpressionMax,length2,g.const(1e-12))))
        detail=g.make(ue.MaterialExpressionTextureSampleParameter2D)
        detail.set_editor_property('parameter_name','DetailNormal')
        detail.set_editor_property('texture',surface_textures['DetailNormal'])
        detail.set_editor_property('sampler_type',ue.MaterialSamplerType.SAMPLERTYPE_NORMAL)
        g.link(g.op(M,uv0,g.scalar('DetailTiling',10.,0,0)),detail,['UVs'])
        n=g.lerp(g.const3([0,0,1]),(detail,'RGB'),g.scalar('DetailStrength',.6,0,0))
        world=g.op(A,g.op(M,g.op(A,g.op(M,tangent,g.mask(n,'r')),g.op(M,bitangent,g.mask(n,'g'))),scale),
                   g.op(M,normal,g.mask(n,'b')))
        g.prop(g.unary(ue.MaterialExpressionNormalize,world),mp.MP_NORMAL)
        g.prop(g.mask(g.vector('SubsurfaceColor',[.62,.20,.11],0,0),'rgb'),mp.MP_SUBSURFACE_COLOR)
        g.prop(g.scalar('SubsurfaceAmount',.38,0,0),mp.MP_OPACITY)
    assert ml.get_material_property_input_node(master, mp.MP_BASE_COLOR) == final
    assert not any(isinstance(n, ue.MaterialExpressionCustom) for n in ml.get_material_expressions(master))
    # Caller owns compile/save of the fresh candidate only.
    report['residentSurface'] = dict(linearVertexColor=True, uvChannel=0, mottle=True,
                                    derivativeNormalDetail=True,skinSubsurface=True,
                                    limitations=['Visual pilot, not runtime acceptance'])

NAMESPACE = '/Game/MikdashV3/Runtime/CurvedVatPacket09'
CUSTOM_FLOATS = 30

def create_candidate(ue, spec, defaults, receipt, *, name, surface_textures=None, subsurface=False, save=False):
    """Explicit coordinator call only, in Engine Entry. No mesh/component/map mutation.

    defaults: exact reviewed VAT textures and decode boxes, supplied by coordinator.
    surface_textures: Mottle/DetailNormal for resident mode, or None for base VAT.
    This compiles a fresh material; compile diagnostics and rendered acceptance are external gates.
    """
    import re
    if not re.fullmatch(r'M_Curved09_[A-Za-z0-9_]{1,48}', name):
        raise ValueError('Fresh isolated material name required')
    world = ue.EditorLevelLibrary.get_editor_world()
    if world is None or world.get_outermost().get_name() != '/Engine/Maps/Entry':
        raise RuntimeError('Coordinator must explicitly load Engine Entry; no fallback/map load here')
    if ue.EditorLevelLibrary.get_pie_worlds(False):
        raise RuntimeError('PIE/game world is forbidden')
    assets = ue.EditorAssetLibrary
    path = NAMESPACE+'/Materials/'+name
    if assets.does_asset_exist(path) or ue.find_object(None, path+'.'+name):
        raise RuntimeError('Candidate already exists; never overwrite')
    for key in ('WalkPositionTexture','WalkNormalTexture','IdlePositionTexture','IdleNormalTexture'):
        if not isinstance(defaults.get(key), ue.Texture):
            raise ValueError('Supply exact reviewed texture: '+key)
    for key in ('WalkMinBBox','WalkSizeBBox','IdleMinBBox','IdleSizeBBox'):
        if len(defaults.get(key,[])) != 3:
            raise ValueError('Supply exact decode box: '+key)
    if surface_textures is not None:
        if set(surface_textures) != {'Mottle','DetailNormal'} or not all(isinstance(t,ue.Texture) for t in surface_textures.values()):
            raise ValueError('Resident surface requires both unchanged source textures')
    if subsurface and surface_textures is None:
        raise ValueError('Skin mode requires resident surface')
    material = _build(ue,spec,NAMESPACE,name,defaults,receipt)
    if material.get_path_name() != path+'.'+name:
        raise RuntimeError('Unexpected candidate path')
    if surface_textures is not None:
        _surface(ue,material,receipt,surface_textures)
    if subsurface:
        material.set_editor_property('shading_model',ue.MaterialShadingModel.MSM_SUBSURFACE)
    expressions=list(ue.MaterialEditingLibrary.get_material_expressions(material))
    indices={int(n.get_editor_property('data_index')) for n in expressions if n.get_class().get_name()=='MaterialExpressionPerInstanceCustomData'}
    if indices != set(range(77)) or any(n.get_class().get_name()=='MaterialExpressionCustom' for n in expressions):
        raise RuntimeError('77-float v9001 stock graph contract failed')
    ue.MaterialEditingLibrary.recompile_material(material)
    if save and not assets.save_loaded_asset(material,False):
        raise RuntimeError('Isolated candidate save failed')
    receipt['angularCandidate']={'path':path,'customFloats':77,'packetVersion':9001,'saved':save,'residentSurface':surface_textures is not None,
        'subsurface':subsurface,'status':'graph_created_compile_requested_NOT_compiler_or_visual_acceptance'}
    return material

