"""Offline deterministic stock-node source generator. Writes only this new study."""
import ast
import hashlib
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
ROOT = BASE.parents[5]
INPUTS = {
    'vat': ROOT/'Scripts/create_crowd_vat_v2.py',
    'history': ROOT/'Scripts/crowd_motion_history_v3.py',
    'surface': ROOT/'Scripts/build_resident_crowd.py',
    'angular': BASE.parent/'RuntimeIntegrationReview03/angular_adapter.py',
}

def extract(text, name):
    node = next(n for n in ast.parse(text).body if isinstance(n,(ast.FunctionDef,ast.ClassDef)) and n.name==name)
    return ast.get_source_segment(text,node)

def replace(text, old, new):
    assert text.count(old)==1, ('Source anchor changed',old)
    return text.replace(old,new)

def generate():
    raw={k:p.read_bytes() for k,p in INPUTS.items()}
    src={k:v.decode('utf-8-sig').replace('\r\n','\n') for k,v in raw.items()}
    parts=['# GENERATED by generate.py; isolated 30-float candidate, no import-time Unreal work.']
    parts += [extract(src['vat'],n) for n in ('_set','_path','Graph','StockGraph','_transform')]
    parts += [extract(src['angular'],n) for n in ('stock_angle','stock_rotate','stock_posed_delta')]
    history=extract(src['history'],'previous_wpo')
    history=replace(history,'for i in HISTORY_LAYOUT','for i in range(11, 26)')
    history=replace(history,'old_local = g.op(add, rest, old_delta)',
        "old_angle = stock_angle(g, time, g.custom_data(28, 0, 0, 0), g.custom_data(29, 0, 0, 0))\n    old_local = stock_rotate(g, g.op(add, rest, old_delta), old_angle)")
    parts.append(history)
    build=extract(src['vat'],'build_master_v2')
    build=replace(build,'def build_master_v2(ue, spec, ns, name, defaults, receipt, previous_wpo_builder=None):',
                  'def _build(ue, spec, ns, name, defaults, receipt):')
    build=replace(build,'wpo = g.op(A, to_world(delta), drift)',
        "angle = stock_angle(g, t, g.custom_data(26, 0, 0, 0), g.custom_data(27, 0, 0, 0))\n    rest = g.make(E.MaterialExpressionPreSkinnedPosition)\n    wpo = g.op(A, to_world(stock_posed_delta(g, rest, delta, angle)), drift)")
    build=replace(build,'if previous_wpo_builder is not None:', 'if True:')
    build=replace(build,'wpo = previous_wpo_builder(', 'wpo = previous_wpo(')
    build=replace(build,"g.link(to_world(normal), n_interp, ['VS'])",
        "g.link(g.unary(E.MaterialExpressionNormalize, to_world(stock_rotate(g, normal, angle))), n_interp, ['VS'])")
    build=replace(build,'    ml.recompile_material(material)\n    if not assets.save_loaded_asset(material, False):\n        raise RuntimeError(\'V2 master save failed\')',
                  '    # Caller validates before optional isolated save; no save/recompile here.')
    parts.append(build)
    surface=extract(src['surface'],'surface')
    surface=replace(surface,'def surface(master, report):','def _surface(ue, master, report, surface_textures):')
    surface=surface.replace('vat.StockGraph','StockGraph')
    surface=replace(surface,"ue.load_asset(resident.TEX_FOLDER+'/T_RV4_SlubMottle')","surface_textures['Mottle']")
    surface=replace(surface,"ue.load_asset(resident.TEX_FOLDER+'/T_RV4_WeaveN')","surface_textures['DetailNormal']")
    surface=surface.replace("STUDY in ('03','04','05','06','07','08','09','10','12')",'True').replace("STUDY!='01'",'True')
    surface=replace(surface,'    ml.recompile_material(master)\n    assert ue.EditorAssetLibrary.save_loaded_asset(master, False)',
                    '    # Caller owns compile/save of the fresh candidate only.')
    parts.append(surface)
    parts.append((BASE/'candidate_api.txt').read_text())
    result='\n\n'.join(parts)+'\n'
    ast.parse(result)
    (BASE/'candidate_builder.py').write_text(result,encoding='utf-8')
    manifest={'scope':'offline generation only','inputs':{str(INPUTS[k].relative_to(ROOT)):hashlib.sha256(v).hexdigest() for k,v in raw.items()},
              'generatorSha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              'apiSha256':hashlib.sha256((BASE/'candidate_api.txt').read_bytes()).hexdigest(),
              'outputSha256':hashlib.sha256((BASE/'candidate_builder.py').read_bytes()).hexdigest()}
    (BASE/'generation.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print('Generated isolated candidate_builder.py; no Unreal loaded')

if __name__=='__main__':
    generate()
